//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.Assets
{
    public partial class AssetManagement
    {
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Button btnAddNew;
        protected global::System.Web.UI.WebControls.Label lblTotalAssets;
        protected global::System.Web.UI.WebControls.Label lblActiveAssets;
        protected global::System.Web.UI.WebControls.Label lblTotalPurchase;
        protected global::System.Web.UI.WebControls.Label lblTotalDepreciation;
        protected global::System.Web.UI.WebControls.Label lblTotalBookValue;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterCategory;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterStatus;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnCalcDepreciation;
        protected global::System.Web.UI.WebControls.GridView gvAssets;
        protected global::System.Web.UI.WebControls.HiddenField hdnAssetId;
        protected global::System.Web.UI.WebControls.Label lblModalTitle;
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
        protected global::System.Web.UI.WebControls.TextBox txtAssetName;
        protected global::System.Web.UI.WebControls.TextBox txtBrand;
        protected global::System.Web.UI.WebControls.TextBox txtModel;
        protected global::System.Web.UI.WebControls.TextBox txtSerialNumber;
        protected global::System.Web.UI.WebControls.TextBox txtPurchaseDate;
        protected global::System.Web.UI.WebControls.TextBox txtPurchasePrice;
        protected global::System.Web.UI.WebControls.TextBox txtUsefulLife;
        protected global::System.Web.UI.WebControls.TextBox txtResidualValue;
        protected global::System.Web.UI.WebControls.TextBox txtWarrantyExpire;
        protected global::System.Web.UI.WebControls.DropDownList ddlVendor;
        protected global::System.Web.UI.WebControls.TextBox txtInvoiceNumber;
        protected global::System.Web.UI.WebControls.TextBox txtLocation;
        protected global::System.Web.UI.WebControls.TextBox txtDepartment;
        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        protected global::System.Web.UI.WebControls.Button btnSaveAsset;
    }
}
