//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Member
{
    public partial class MemberCard
    {
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divCard;
        protected global::System.Web.UI.WebControls.Literal litCardBg;
        protected global::System.Web.UI.WebControls.Panel pnlExpired;
        protected global::System.Web.UI.WebControls.Literal litTier;
        protected global::System.Web.UI.WebControls.Literal litName;
        protected global::System.Web.UI.WebControls.Literal litPhone;
        protected global::System.Web.UI.WebControls.Literal litSince;
        protected global::System.Web.UI.WebControls.Literal litPoints;
        protected global::System.Web.UI.WebControls.Literal litExpiry;
        protected global::System.Web.UI.WebControls.Panel pnlDisc;
        protected global::System.Web.UI.WebControls.Literal litWeekday;
        protected global::System.Web.UI.WebControls.Literal litWeekend;
        protected global::System.Web.UI.WebControls.Panel pnlBenefits;
        protected global::System.Web.UI.WebControls.Literal litBenefits;
        protected global::System.Web.UI.WebControls.Repeater rptVouchers;
        protected global::System.Web.UI.WebControls.Panel pnlNoVoucher;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
    }
}
