//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Member
{
    public partial class MemberLogin
    {
        protected global::System.Web.UI.WebControls.Panel pnlErr;
        protected global::System.Web.UI.WebControls.Literal litErr;
        protected global::System.Web.UI.WebControls.Panel pnlLogin;
        protected global::System.Web.UI.WebControls.TextBox txtPhone;
        protected global::System.Web.UI.WebControls.TextBox txtPin;
        protected global::System.Web.UI.WebControls.Button btnLogin;
        protected global::System.Web.UI.WebControls.Panel pnlSetPin;
        protected global::System.Web.UI.WebControls.TextBox txtNewPin;
        protected global::System.Web.UI.WebControls.TextBox txtNewPin2;
        protected global::System.Web.UI.WebControls.Button btnSetPin;
    }
}
