//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.Payroll
{
    public partial class PayrollDetail
    {
        /// <summary>
        /// lblPeriod control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPeriod;

        /// <summary>
        /// lblEmployeeName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEmployeeName;

        /// <summary>
        /// lblPosition control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPosition;

        /// <summary>
        /// lblEmployeeCode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEmployeeCode;

        /// <summary>
        /// lblDepartment control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblDepartment;

        /// <summary>
        /// lblBaseSalary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblBaseSalary;

        /// <summary>
        /// lblOTAmount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblOTAmount;

        /// <summary>
        /// lblBonus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblBonus;

        /// <summary>
        /// lblAllowances control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAllowances;

        /// <summary>
        /// lblTotalEarnings control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalEarnings;

        /// <summary>
        /// lblLeaveDeduction control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblLeaveDeduction;

        /// <summary>
        /// lblSocialSecurity control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSocialSecurity;

        /// <summary>
        /// lblTax control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTax;

        /// <summary>
        /// lblOtherDeductions control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblOtherDeductions;

        /// <summary>
        /// lblTotalDeductions control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalDeductions;

        /// <summary>
        /// lblWorkDays control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblWorkDays;

        /// <summary>
        /// lblLeaveDays control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblLeaveDays;

        /// <summary>
        /// lblNetSalary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNetSalary;

        /// <summary>
        /// pnlOTDetails control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlOTDetails;

        /// <summary>
        /// gvOTDetails control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvOTDetails;

        /// <summary>
        /// btnPrint control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnPrint;

        /// <summary>
        /// btnPrintVoucher control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnPrintVoucher;

        /// <summary>
        /// btnGenerateVoucher control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnGenerateVoucher;
    }
}
