//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.Payroll
{
    public partial class PayrollManagement
    {
        /// <summary>
        /// ddlYear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;

        /// <summary>
        /// ddlMonth control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlMonth;

        /// <summary>
        /// btnGeneratePayroll control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnGeneratePayroll;

        /// <summary>
        /// btnApprovePayroll control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnApprovePayroll;

        /// <summary>
        /// pnlStats control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlStats;

        /// <summary>
        /// lblTotalEmployees control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalEmployees;

        /// <summary>
        /// lblTotalGrossPay control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalGrossPay;

        /// <summary>
        /// lblTotalDeductions control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalDeductions;

        /// <summary>
        /// lblTotalNetPay control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalNetPay;

        /// <summary>
        /// gvPayroll control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvPayroll;
    }
}
