//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Guest
{
    public partial class ActivityBooking
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Literal litRoom;

        protected global::System.Web.UI.WebControls.Panel pnlMsg;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divMsg;
        protected global::System.Web.UI.WebControls.Literal litMsg;

        protected global::System.Web.UI.WebControls.Panel pnlMyBookings;
        protected global::System.Web.UI.WebControls.Repeater rptMyBookings;

        protected global::System.Web.UI.WebControls.Panel pnlPickActivity;
        protected global::System.Web.UI.WebControls.Repeater rptActivities;
        protected global::System.Web.UI.WebControls.Panel pnlNoActivities;

        protected global::System.Web.UI.WebControls.Panel pnlPickSlot;
        protected global::System.Web.UI.WebControls.Literal litActivityName;
        protected global::System.Web.UI.WebControls.Panel pnlRules;
        protected global::System.Web.UI.WebControls.Literal litRules;
        protected global::System.Web.UI.WebControls.DropDownList ddlDate;
        protected global::System.Web.UI.WebControls.Literal litSlots;
        protected global::System.Web.UI.WebControls.HiddenField hfSlots;
        protected global::System.Web.UI.WebControls.Panel pnlParticipants;
        protected global::System.Web.UI.WebControls.TextBox txtParticipants;
        protected global::System.Web.UI.WebControls.TextBox txtNotes;
        protected global::System.Web.UI.WebControls.Button btnBackToList;
        protected global::System.Web.UI.WebControls.Button btnNextToPay;

        protected global::System.Web.UI.WebControls.Panel pnlPay;
        protected global::System.Web.UI.WebControls.Literal litSumActivity;
        protected global::System.Web.UI.WebControls.Literal litSumDate;
        protected global::System.Web.UI.WebControls.Literal litSumTime;
        protected global::System.Web.UI.WebControls.Literal litSumAmount;
        protected global::System.Web.UI.WebControls.Panel pnlPayMethods;
        protected global::System.Web.UI.WebControls.RadioButtonList rblPayment;
        protected global::System.Web.UI.WebControls.Panel pnlSlip;
        protected global::System.Web.UI.WebControls.FileUpload fuSlip;
        protected global::System.Web.UI.WebControls.Button btnBackToSlot;
        protected global::System.Web.UI.WebControls.Button btnConfirm;
    }
}
