//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Guest
{
    public partial class Activities
    {
        protected global::System.Web.UI.WebControls.Label lblOnsiteCount;
        protected global::System.Web.UI.WebControls.Label lblOffsiteCount;
        protected global::System.Web.UI.WebControls.Repeater rptOnsiteActivities;
        protected global::System.Web.UI.WebControls.Label lblNoOnsite;
        protected global::System.Web.UI.WebControls.Repeater rptOffsiteActivities;
        protected global::System.Web.UI.WebControls.Label lblNoOffsite;
    }
}
