//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Guest
{


    public partial class Amenities
    {

        /// <summary>
        /// pnlNotReady control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move the field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlNotReady;

        /// <summary>
        /// pnlNoItems control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move the field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlNoItems;

        /// <summary>
        /// pnlOrder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move the field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlOrder;

        /// <summary>
        /// txtNote control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move the field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtNote;

        /// <summary>
        /// rptRequests control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move the field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptRequests;

        /// <summary>
        /// pnlNoRequests control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move the field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlNoRequests;

        /// <summary>
        /// hfCart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move the field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfCart;

        /// <summary>
        /// btnSubmit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move the field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSubmit;
    }
}
