//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Guest
{

    public partial class Chat
    {

        /// <summary>
        /// rptMessages control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptMessages;

        /// <summary>
        /// pnlEmptyChat control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlEmptyChat;

        /// <summary>
        /// txtMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtMessage;

        /// <summary>
        /// btnSend control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSend;

        /// <summary>
        /// hfReservationId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfReservationId;
    }
}
