//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Guest
{
    public partial class Concierge
    {
        protected global::System.Web.UI.WebControls.HiddenField hfServiceType;
        protected global::System.Web.UI.WebControls.TextBox txtServiceName;
        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        protected global::System.Web.UI.WebControls.TextBox txtPreferredDate;
        protected global::System.Web.UI.WebControls.TextBox txtNumberOfGuests;
        protected global::System.Web.UI.WebControls.Button btnSubmitRequest;
        protected global::System.Web.UI.WebControls.Repeater rptRequests;
        protected global::System.Web.UI.WebControls.Label lblNoRequests;
    }
}
