//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Guest
{


    public partial class Dashboard
    {

        /// <summary>
        /// lblGuestName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move the field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblGuestName;

        /// <summary>
        /// lblRoomName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move the field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblRoomName;

        /// <summary>
        /// lblCheckIn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move the field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCheckIn;

        /// <summary>
        /// lblCheckOut control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move the field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCheckOut;

        /// <summary>
        /// lblBalanceDue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move the field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblBalanceDue;

        /// <summary>
        /// lblLoyaltyPoints control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move the field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblLoyaltyPoints;

        /// <summary>
        /// lblRSOrders control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move the field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblRSOrders;

        /// <summary>
        /// lblPendingRequests control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move the field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblPendingRequests;

        /// <summary>
        /// btnLogout control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move the field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnLogout;

        /// <summary>Feature-flag placeholders (ซ่อนการ์ด/ปุ่มตามสวิตช์ฟีเจอร์)</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phQaRoomService;
        protected global::System.Web.UI.WebControls.PlaceHolder phQaHousekeeping;
        protected global::System.Web.UI.WebControls.PlaceHolder phPromoReview;
        protected global::System.Web.UI.WebControls.PlaceHolder phSvcRoomService;
        protected global::System.Web.UI.WebControls.PlaceHolder phSvcHousekeeping;
        protected global::System.Web.UI.WebControls.PlaceHolder phSvcActivities;
        protected global::System.Web.UI.WebControls.PlaceHolder phSvcActivityBooking;
        protected global::System.Web.UI.WebControls.PlaceHolder phSvcPoints;
        protected global::System.Web.UI.WebControls.PlaceHolder phSvcReview;
        protected global::System.Web.UI.WebControls.PlaceHolder phSvcChat;
        protected global::System.Web.UI.WebControls.PlaceHolder phBnRoomService;
        protected global::System.Web.UI.WebControls.PlaceHolder phBnActivities;
        protected global::System.Web.UI.WebControls.PlaceHolder phBnReview;
    }
}
