//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Guest
{
    public partial class MyPoints
    {
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl alertBox;
        protected global::System.Web.UI.WebControls.Label lblAlert;
        protected global::System.Web.UI.WebControls.Label lblRedeemable;
        protected global::System.Web.UI.WebControls.Label lblYearly;
        protected global::System.Web.UI.WebControls.Label lblYear;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl tierEmblem;
        protected global::System.Web.UI.WebControls.Label lblTierName;
        protected global::System.Web.UI.WebControls.Label lblTierHint;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl tierBar;
        protected global::System.Web.UI.WebControls.Label lblProgressNow;
        protected global::System.Web.UI.WebControls.Label lblProgressNext;
        protected global::System.Web.UI.WebControls.Repeater rptRewards;
        protected global::System.Web.UI.WebControls.Label lblNoRewards;
        protected global::System.Web.UI.WebControls.Repeater rptVouchers;
        protected global::System.Web.UI.WebControls.Label lblNoVouchers;
        protected global::System.Web.UI.WebControls.Repeater rptTransactions;
        protected global::System.Web.UI.WebControls.Label lblNoTxn;
    }
}
