//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Voucher
{
    public partial class OcrUpload
    {
        protected global::System.Web.UI.WebControls.FileUpload fuOcr;
        protected global::System.Web.UI.WebControls.DropDownList ddlTargetType;
        protected global::System.Web.UI.WebControls.Button btnScan;
        protected global::System.Web.UI.WebControls.Literal litStatus;
        protected global::System.Web.UI.WebControls.Panel pnlReview;
        protected global::System.Web.UI.WebControls.Literal litMeta;
        protected global::System.Web.UI.WebControls.TextBox txtVendorName;
        protected global::System.Web.UI.WebControls.TextBox txtVendorTaxId;
        protected global::System.Web.UI.WebControls.TextBox txtDocNumber;
        protected global::System.Web.UI.WebControls.TextBox txtDocDate;
        protected global::System.Web.UI.WebControls.TextBox txtSubTotal;
        protected global::System.Web.UI.WebControls.TextBox txtVat;
        protected global::System.Web.UI.WebControls.TextBox txtTotal;
        protected global::System.Web.UI.WebControls.Literal litSuggested;
        protected global::System.Web.UI.WebControls.Button btnCreate;
        protected global::System.Web.UI.WebControls.Literal litResult;
        protected global::System.Web.UI.WebControls.HiddenField hfScanId;
    }
}
