//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Voucher
{
    public partial class VoucherList
    {
        protected global::System.Web.UI.WebControls.Button btnExport;
        protected global::System.Web.UI.WebControls.LinkButton lnkStatAll;
        protected global::System.Web.UI.WebControls.Label lblStatAll;
        protected global::System.Web.UI.WebControls.LinkButton lnkStatActive;
        protected global::System.Web.UI.WebControls.Label lblStatActive;
        protected global::System.Web.UI.WebControls.LinkButton lnkStatUsed;
        protected global::System.Web.UI.WebControls.Label lblStatUsed;
        protected global::System.Web.UI.WebControls.LinkButton lnkStatExpired;
        protected global::System.Web.UI.WebControls.Label lblStatExpired;
        protected global::System.Web.UI.WebControls.LinkButton lnkStatCancelled;
        protected global::System.Web.UI.WebControls.Label lblStatCancelled;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.TextBox txtDateFrom;
        protected global::System.Web.UI.WebControls.TextBox txtDateTo;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.Label lblResultCount;
        protected global::System.Web.UI.WebControls.Label lblTotalSales;
        protected global::System.Web.UI.WebControls.GridView gvVouchers;
        protected global::System.Web.UI.WebControls.Button btnPrevPage;
        protected global::System.Web.UI.WebControls.Label lblCurrentPage;
        protected global::System.Web.UI.WebControls.Label lblTotalPages;
        protected global::System.Web.UI.WebControls.Button btnNextPage;
    }
}
