//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.Report
{
    public partial class CustomerAnalytics
    {
        /// <summary>
        /// ddlYear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;

        /// <summary>
        /// ddlCustomerType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCustomerType;

        /// <summary>
        /// ddlLimit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlLimit;

        /// <summary>
        /// btnExport control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnExport;

        /// <summary>
        /// litTotalCustomers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalCustomers;

        /// <summary>
        /// litNewCustomers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNewCustomers;

        /// <summary>
        /// litReturningCustomers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litReturningCustomers;

        /// <summary>
        /// litVIPCustomers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litVIPCustomers;

        /// <summary>
        /// litSelectedYear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSelectedYear;

        /// <summary>
        /// litRepeatCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRepeatCount;

        /// <summary>
        /// gvRepeatCustomers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvRepeatCustomers;

        /// <summary>
        /// litDisplayCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litDisplayCount;

        /// <summary>
        /// litTotalCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalCount;

        /// <summary>
        /// gvAllCustomers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvAllCustomers;

        /// <summary>
        /// hfSegmentationData control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfSegmentationData;

        /// <summary>
        /// hfTopCustomersData control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfTopCustomersData;

        /// <summary>
        /// hfTopCustomersLabels control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfTopCustomersLabels;

        /// <summary>
        /// pnlReservationDetail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlReservationDetail;

        /// <summary>
        /// litSelectedCustomer control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSelectedCustomer;

        /// <summary>
        /// btnCloseDetail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCloseDetail;

        /// <summary>
        /// gvReservationDetail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvReservationDetail;

        /// <summary>
        /// hfMonthlyTrendLabels control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfMonthlyTrendLabels;

        /// <summary>
        /// hfMonthlyTrendData control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfMonthlyTrendData;

        /// <summary>
        /// hfMonthlyTrendCustomers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfMonthlyTrendCustomers;

        /// <summary>
        /// litAvgSpendingPerCustomer control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAvgSpendingPerCustomer;

        /// <summary>
        /// litTotalReservations control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalReservations;

        /// <summary>
        /// litReturnRate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litReturnRate;

        /// <summary>
        /// litAvgDaysBetweenVisits control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAvgDaysBetweenVisits;

        /// <summary>
        /// pnlAtRiskCustomers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlAtRiskCustomers;

        /// <summary>
        /// litAtRiskCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAtRiskCount;

        /// <summary>
        /// rptAtRiskCustomers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptAtRiskCustomers;

        /// <summary>
        /// pnlNoAtRisk control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoAtRisk;

        /// <summary>
        /// litCLVTier1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCLVTier1;

        /// <summary>
        /// litCLVTier2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCLVTier2;

        /// <summary>
        /// litCLVTier3 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCLVTier3;

        /// <summary>
        /// litCLVTier4 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCLVTier4;

        /// <summary>
        /// litCLVTier5 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCLVTier5;

        /// <summary>
        /// hfCLVDistribution control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfCLVDistribution;

        /// <summary>
        /// rptAccommodationAffinity control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptAccommodationAffinity;
    }
}
