//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.ChannelManager
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Label lblDirectBookings;
        protected global::System.Web.UI.WebControls.Label lblDirectRevenue;
        protected global::System.Web.UI.WebControls.Label lblTotalBookings;
        protected global::System.Web.UI.WebControls.Label lblTotalRevenue;
        protected global::System.Web.UI.WebControls.Label lblAvgRate;
        protected global::System.Web.UI.WebControls.Label lblOccupancy;
    }
}
