//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.GuestExperience
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Label lblOverallScore;
        protected global::System.Web.UI.WebControls.Label lblCleanliness;
        protected global::System.Web.UI.WebControls.Label lblService;
        protected global::System.Web.UI.WebControls.Label lblValue;
        protected global::System.Web.UI.WebControls.Label lblLocation;
        protected global::System.Web.UI.WebControls.Label lblAvgResponse;
        protected global::System.Web.UI.WebControls.Label lblResponseRate;
        protected global::System.Web.UI.WebControls.Label lblPendingMessages;
        protected global::System.Web.UI.WebControls.Label lblReturning;
        protected global::System.Web.UI.WebControls.Label lblLoyaltyMembers;
        protected global::System.Web.UI.WebControls.Label lblPointsRedeemed;
    }
}
