//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.Settings
{
    public partial class ActivityManagement
    {
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Literal litMessage;
        protected global::System.Web.UI.WebControls.LinkButton btnTabList;
        protected global::System.Web.UI.WebControls.LinkButton btnTabEdit;
        protected global::System.Web.UI.WebControls.LinkButton btnTabBookings;
        protected global::System.Web.UI.WebControls.Literal litPendingBadge;

        protected global::System.Web.UI.WebControls.Panel pnlList;
        protected global::System.Web.UI.WebControls.GridView gvActivities;

        protected global::System.Web.UI.WebControls.Panel pnlEdit;
        protected global::System.Web.UI.WebControls.Literal litEditTitle;
        protected global::System.Web.UI.WebControls.HiddenField hfActivityId;
        protected global::System.Web.UI.WebControls.TextBox txtName;
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
        protected global::System.Web.UI.WebControls.TextBox txtLocation;
        protected global::System.Web.UI.WebControls.TextBox txtShortDesc;
        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        protected global::System.Web.UI.WebControls.TextBox txtRules;
        protected global::System.Web.UI.WebControls.FileUpload fuImage;
        protected global::System.Web.UI.WebControls.TextBox txtIcon;
        protected global::System.Web.UI.WebControls.TextBox txtOrder;
        protected global::System.Web.UI.WebControls.DropDownList ddlPricingMode;
        protected global::System.Web.UI.WebControls.TextBox txtPrice;
        protected global::System.Web.UI.WebControls.TextBox txtDuration;
        protected global::System.Web.UI.WebControls.CheckBox chkBookable;
        protected global::System.Web.UI.WebControls.TextBox txtCapacity;
        protected global::System.Web.UI.WebControls.TextBox txtOpenTime;
        protected global::System.Web.UI.WebControls.TextBox txtCloseTime;
        protected global::System.Web.UI.WebControls.TextBox txtSlotMinutes;
        protected global::System.Web.UI.WebControls.TextBox txtMaxSlots;
        protected global::System.Web.UI.WebControls.TextBox txtAdvanceDays;
        protected global::System.Web.UI.WebControls.TextBox txtMaxParticipants;
        protected global::System.Web.UI.WebControls.CheckBox chkRequireApproval;
        protected global::System.Web.UI.WebControls.CheckBox chkShowWebsite;
        protected global::System.Web.UI.WebControls.CheckBox chkShowPortal;
        protected global::System.Web.UI.WebControls.CheckBox chkActive;
        protected global::System.Web.UI.WebControls.TextBox txtContact;
        protected global::System.Web.UI.WebControls.TextBox txtMapUrl;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnCancelEdit;

        protected global::System.Web.UI.WebControls.Panel pnlBookings;
        protected global::System.Web.UI.WebControls.TextBox txtFrom;
        protected global::System.Web.UI.WebControls.TextBox txtTo;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatusFilter;
        protected global::System.Web.UI.WebControls.Button btnFilter;
        protected global::System.Web.UI.WebControls.GridView gvBookings;
    }
}
