//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.Settings
{
    public partial class AIKnowledgeBase
    {
        protected global::System.Web.UI.WebControls.HiddenField hfInitData;
    }
}
