//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.Settings
{


    public partial class BookingPolicies
    {

        /// <summary>
        /// litMsg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMsg;

        /// <summary>
        /// litInfo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litInfo;

        /// <summary>
        /// txtTerms control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTerms;

        /// <summary>
        /// txtPrivacy control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPrivacy;

        /// <summary>
        /// txtRefund control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRefund;

        /// <summary>
        /// txtCancel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCancel;

        /// <summary>
        /// btnSave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSave;

        /// <summary>
        /// litPreview control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPreview;
    }
}
