//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.Settings
{
    public partial class LineAccount
    {
        protected global::System.Web.UI.WebControls.Panel pnlMsg;
        protected global::System.Web.UI.WebControls.Literal litMsg;

        protected global::System.Web.UI.WebControls.Panel pnlNotConfigured;
        protected global::System.Web.UI.WebControls.Literal litAvatar;
        protected global::System.Web.UI.WebControls.Literal litMyName;
        protected global::System.Web.UI.WebControls.Literal litMyStatus;
        protected global::System.Web.UI.WebControls.Button btnLink;
        protected global::System.Web.UI.WebControls.Button btnTestMe;
        protected global::System.Web.UI.WebControls.Button btnUnlink;
        protected global::System.Web.UI.WebControls.CheckBox chkNotify;

        protected global::System.Web.UI.WebControls.Panel pnlTeam;
        protected global::System.Web.UI.WebControls.GridView gvTeam;
        protected global::System.Web.UI.WebControls.TextBox txtBroadcast;
        protected global::System.Web.UI.WebControls.Button btnBroadcast;

        protected global::System.Web.UI.WebControls.Panel pnlConfig;
        protected global::System.Web.UI.WebControls.DropDownList ddlEnabled;
        protected global::System.Web.UI.WebControls.TextBox txtChannelId;
        protected global::System.Web.UI.WebControls.TextBox txtChannelSecret;
        protected global::System.Web.UI.WebControls.Literal litSecretStatus;
        protected global::System.Web.UI.WebControls.TextBox txtCallback;
        protected global::System.Web.UI.WebControls.Button btnSaveConfig;
    }
}
