//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.Settings
{


    public partial class PaymentGatewaySettings
    {

        /// <summary>
        /// litMsg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMsg;

        /// <summary>
        /// litWebhookUrl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litWebhookUrl;

        /// <summary>
        /// litReturnUrl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litReturnUrl;

        /// <summary>
        /// litPayUrl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPayUrl;

        /// <summary>
        /// phSettings control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phSettings;

        /// <summary>
        /// btnSave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSave;

        /// <summary>
        /// btnTest control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnTest;

        /// <summary>
        /// btnReload control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnReload;

        /// <summary>
        /// pnlTest control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlTest;

        /// <summary>
        /// litTest control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTest;

        /// <summary>
        /// gvTxn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvTxn;
    }
}
