//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.Settings
{


    public partial class PaymentChannelsSettings
    {

        /// <summary>
        /// litMsg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMsg;

        /// <summary>
        /// litStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litStatus;

        /// <summary>
        /// litPreview control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPreview;

        /// <summary>
        /// txtPolicy control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPolicy;

        /// <summary>
        /// phRows control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phRows;

        /// <summary>
        /// btnSave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
