//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.Settings
{
    public partial class PermissionGroups
    {
        protected global::System.Web.UI.WebControls.Panel pnlMsg;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divMsg;
        protected global::System.Web.UI.WebControls.Literal litMsg;
        protected global::System.Web.UI.WebControls.Literal litGroups;
        protected global::System.Web.UI.WebControls.TextBox txtNewGroup;
        protected global::System.Web.UI.WebControls.DropDownList ddlNewBaseRole;
        protected global::System.Web.UI.WebControls.Button btnAddGroup;
        protected global::System.Web.UI.WebControls.Panel pnlEdit;
        protected global::System.Web.UI.WebControls.Literal litGroupName;
        protected global::System.Web.UI.WebControls.TextBox txtGroupName;
        protected global::System.Web.UI.WebControls.TextBox txtGroupDesc;
        protected global::System.Web.UI.WebControls.Literal litMatrix;
        protected global::System.Web.UI.WebControls.Button btnDeleteGroup;
        protected global::System.Web.UI.WebControls.Button btnSavePerm;
        protected global::System.Web.UI.WebControls.Literal litMembers;
        protected global::System.Web.UI.WebControls.DropDownList ddlAddMember;
        protected global::System.Web.UI.WebControls.Button btnAddMember;
    }
}
