//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.Settings
{


    public partial class PetStaySettings
    {

        /// <summary>
        /// litMsg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMsg;

        /// <summary>
        /// litInfo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litInfo;

        /// <summary>
        /// chkEnabled control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkEnabled;

        /// <summary>
        /// ddlFeeUnit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFeeUnit;

        /// <summary>
        /// phRooms control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phRooms;

        /// <summary>
        /// txtPetPolicy control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPetPolicy;

        /// <summary>
        /// btnSave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSave;

        /// <summary>
        /// litPreview control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPreview;
    }
}
