//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.Settings
{


    public partial class SecurityDepositSettings
    {

        /// <summary>
        /// litMsg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMsg;

        /// <summary>
        /// litReady control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litReady;

        /// <summary>
        /// chkEnabled control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkEnabled;

        /// <summary>
        /// txtDefault control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDefault;

        /// <summary>
        /// txtWarnHours control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtWarnHours;

        /// <summary>
        /// txtBulk control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBulk;

        /// <summary>
        /// btnBulk control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnBulk;

        /// <summary>
        /// btnClear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnClear;

        /// <summary>
        /// phRooms control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phRooms;

        /// <summary>
        /// btnSave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSave;

        /// <summary>
        /// litHolds control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litHolds;
    }
}
