//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.Settings
{
    public partial class SystemSettings
    {
        protected global::System.Web.UI.WebControls.Panel pnlMsg;
        protected global::System.Web.UI.WebControls.Literal litMsg;
        protected global::System.Web.UI.WebControls.Literal litGroups;
        protected global::System.Web.UI.WebControls.Button btnTestTelegram;
        protected global::System.Web.UI.WebControls.Button btnTestLine;
        protected global::System.Web.UI.WebControls.Button btnTestEmail;
        protected global::System.Web.UI.WebControls.TextBox txtTestEmailTo;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divRes;
        protected global::System.Web.UI.WebControls.Literal litRes;
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
