//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.RoomService
{
    public partial class OrderSettings
    {
        protected global::System.Web.UI.WebControls.Label lblCurrentStatus;
        protected global::System.Web.UI.WebControls.CheckBox chkEnabled;
        protected global::System.Web.UI.WebControls.DropDownList ddlMode;
        protected global::System.Web.UI.WebControls.TextBox txtOpenTime;
        protected global::System.Web.UI.WebControls.TextBox txtCloseTime;
        protected global::System.Web.UI.WebControls.TextBox txtClosedMessage;
        protected global::System.Web.UI.WebControls.DropDownList ddlServiceChargeMode;
        protected global::System.Web.UI.WebControls.TextBox txtServiceChargeValue;
        protected global::System.Web.UI.WebControls.TextBox txtServiceChargeMax;
        protected global::System.Web.UI.WebControls.TextBox txtServiceChargeLabel;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Label lblSaved;
    }
}
