//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.RoomService
{
    public partial class OrderManagement
    {
        protected global::System.Web.UI.WebControls.Panel pnlPendingBadge;
        protected global::System.Web.UI.WebControls.Label lblPendingCount;
        protected global::System.Web.UI.WebControls.Repeater rptOrderList;
        protected global::System.Web.UI.WebControls.Panel pnlNoOrders;
        protected global::System.Web.UI.WebControls.Panel pnlOrderDetail;
        protected global::System.Web.UI.WebControls.Label lblOrderNumber;
        protected global::System.Web.UI.WebControls.Label lblRoomName;
        protected global::System.Web.UI.WebControls.Label lblGuestName;
        protected global::System.Web.UI.WebControls.Label lblPhone;
        protected global::System.Web.UI.WebControls.Label lblOrderTime;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.Label lblPayment;
        protected global::System.Web.UI.WebControls.Label lblDeliveryNote;
        protected global::System.Web.UI.WebControls.Repeater rptOrderItems;
        protected global::System.Web.UI.WebControls.Label lblTotalAmount;
        protected global::System.Web.UI.WebControls.Button btnClaim;
        protected global::System.Web.UI.WebControls.Button btnDelivered;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        protected global::System.Web.UI.WebControls.Panel pnlSelectOrder;
        protected global::System.Web.UI.WebControls.HiddenField hfSelectedOrder;
        protected global::System.Web.UI.WebControls.Button btnLoadOrder;
    }
}
