//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.Housekeeping
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Label lblCleanCount;
        protected global::System.Web.UI.WebControls.Label lblDirtyCount;
        protected global::System.Web.UI.WebControls.Label lblInspectingCount;
        protected global::System.Web.UI.WebControls.Label lblOccupiedCount;
        protected global::System.Web.UI.WebControls.Panel pnlDirtyRooms;
        protected global::System.Web.UI.WebControls.Repeater rptDirtyRooms;
        protected global::System.Web.UI.WebControls.Label lblNoDirtyRooms;
        protected global::System.Web.UI.WebControls.Repeater rptAllRooms;
    }
}
