//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.Maintenance
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Label lblPending;
        protected global::System.Web.UI.WebControls.Label lblInProgress;
        protected global::System.Web.UI.WebControls.Label lblCompleted;
        protected global::System.Web.UI.WebControls.Repeater rptRequests;
        protected global::System.Web.UI.WebControls.Label lblNoRequests;
    }
}
