//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.Notifications
{


    public partial class Settings
    {

        /// <summary>
        /// litMsg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMsg;

        /// <summary>
        /// litTgToken control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTgToken;

        /// <summary>
        /// chkTelegram control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkTelegram;

        /// <summary>
        /// txtTgTarget control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTgTarget;

        /// <summary>
        /// litLineToken control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litLineToken;

        /// <summary>
        /// chkLine control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkLine;

        /// <summary>
        /// txtLineTarget control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLineTarget;

        /// <summary>
        /// btnTestTg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnTestTg;

        /// <summary>
        /// btnTestLine control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnTestLine;

        /// <summary>
        /// pnlTest control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlTest;

        /// <summary>
        /// litTest control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTest;

        /// <summary>
        /// txtQuietFrom control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtQuietFrom;

        /// <summary>
        /// txtQuietTo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtQuietTo;

        /// <summary>
        /// chkQuietUrgent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkQuietUrgent;

        /// <summary>
        /// phEvents control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phEvents;

        /// <summary>
        /// btnSave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSave;

        /// <summary>
        /// btnAllTgOn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAllTgOn;

        /// <summary>
        /// btnAllTgOff control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAllTgOff;

        /// <summary>
        /// gvLog control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvLog;
    }
}
