//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Affiliate
{
    public partial class Default
    {
        protected global::System.Web.UI.WebControls.Label lblWelcomeName;
        protected global::System.Web.UI.WebControls.Label TextBox1;
        protected global::System.Web.UI.WebControls.Label TextBox2;
        protected global::System.Web.UI.WebControls.Label TextBox3;
        protected global::System.Web.UI.WebControls.Label TextBox4;
        protected global::System.Web.UI.WebControls.Label TextBox5;
        protected global::System.Web.UI.WebControls.Label TextBox6;
        protected global::System.Web.UI.WebControls.Label lblPendingAmount;
        protected global::System.Web.UI.WebControls.DropDownList DropDownList1;
        protected global::System.Web.UI.WebControls.Button Button2;
        protected global::System.Web.UI.WebControls.GridView GridView1;
    }
}
