//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Account
{


    public partial class NextAccPayments
    {

        /// <summary>
        /// txtFrom control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFrom;

        /// <summary>
        /// txtTo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTo;

        /// <summary>
        /// btnFetch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnFetch;

        /// <summary>
        /// lblStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStatus;

        /// <summary>
        /// rptDocs control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptDocs;

        /// <summary>
        /// phEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phEmpty;
    }
}
