//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Account
{
    public partial class SendEtax
    {
        protected global::System.Web.UI.WebControls.Literal litMsg;
        protected global::System.Web.UI.WebControls.Panel pnlForm;
        protected global::System.Web.UI.WebControls.Literal litReceipt;
        protected global::System.Web.UI.WebControls.Literal litGuest;
        protected global::System.Web.UI.WebControls.Literal litAmount;
        protected global::System.Web.UI.WebControls.TextBox txtTo;
        protected global::System.Web.UI.WebControls.TextBox txtCc;
        protected global::System.Web.UI.WebControls.TextBox txtSubject;
        protected global::System.Web.UI.WebControls.TextBox txtBody;
        protected global::System.Web.UI.WebControls.CheckBox chkPdf;
        protected global::System.Web.UI.WebControls.CheckBox chkXml;
        protected global::System.Web.UI.WebControls.Button btnSend;
        protected global::System.Web.UI.WebControls.HyperLink lnkPreview;
    }
}
