//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.Leave
{
    public partial class LeaveReplacement
    {
        /// <summary>
        /// pnlAlert control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlAlert;

        /// <summary>
        /// lblAlertMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAlertMessage;

        /// <summary>
        /// lblApprovedLeaves control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblApprovedLeaves;

        /// <summary>
        /// lblReplacedLeaves control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblReplacedLeaves;

        /// <summary>
        /// lblPendingReplacement control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPendingReplacement;

        /// <summary>
        /// ddlYear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;

        /// <summary>
        /// ddlReplacementStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlReplacementStatus;

        /// <summary>
        /// txtSearchEmployee control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearchEmployee;

        /// <summary>
        /// btnSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;

        /// <summary>
        /// gvLeaveRequests control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvLeaveRequests;

        /// <summary>
        /// hfSelectedLeaveId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfSelectedLeaveId;

        /// <summary>
        /// txtReplacementDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtReplacementDate;

        /// <summary>
        /// btnConfirmReplacement control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConfirmReplacement;
    }
}
