//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.Leave
{
    public partial class LeaveManagement
    {
        /// <summary>
        /// lblPendingRequests control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPendingRequests;

        /// <summary>
        /// lblApprovedThisYear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblApprovedThisYear;

        /// <summary>
        /// lblRejectedThisYear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblRejectedThisYear;

        /// <summary>
        /// lblTotalDays control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalDays;

        /// <summary>
        /// ddlStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;

        /// <summary>
        /// ddlYear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;

        /// <summary>
        /// txtSearchEmployee control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearchEmployee;

        /// <summary>
        /// btnSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;

        /// <summary>
        /// gvLeaveRequests control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvLeaveRequests;
    }
}
