//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.Leave
{
    public partial class LeaveHistory
    {
        /// <summary>
        /// lblEmployeeName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEmployeeName;

        /// <summary>
        /// lblPosition control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPosition;

        /// <summary>
        /// ddlYear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;

        /// <summary>
        /// ddlLeaveType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlLeaveType;

        /// <summary>
        /// ddlStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;

        /// <summary>
        /// btnClear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnClear;

        /// <summary>
        /// lblTotalQuota control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalQuota;

        /// <summary>
        /// lblTotalUsed control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalUsed;

        /// <summary>
        /// lblTotalRemaining control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalRemaining;

        /// <summary>
        /// lblTotalRequests control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalRequests;

        /// <summary>
        /// lblSelectedYear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSelectedYear;

        /// <summary>
        /// gvLeaveQuota control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvLeaveQuota;

        /// <summary>
        /// lblResultCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblResultCount;

        /// <summary>
        /// gvLeaveHistory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvLeaveHistory;
    }
}
