//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.Leave
{
    public partial class LeaveRequest
    {
        /// <summary>
        /// pnlMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// pnlSupervisorMode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSupervisorMode;

        /// <summary>
        /// ddlSubordinates control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlSubordinates;

        /// <summary>
        /// lblEmployeeName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEmployeeName;

        /// <summary>
        /// lblPosition control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPosition;

        /// <summary>
        /// lblTotalQuota control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalQuota;

        /// <summary>
        /// lblTotalUsed control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalUsed;

        /// <summary>
        /// lblTotalRemainingDays control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalRemainingDays;

        /// <summary>
        /// lblPendingRequests control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPendingRequests;

        /// <summary>
        /// lblYear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblYear;

        /// <summary>
        /// gvLeaveQuota control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvLeaveQuota;

        /// <summary>
        /// ddlLeaveType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlLeaveType;

        /// <summary>
        /// txtTotalDays control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTotalDays;

        /// <summary>
        /// txtStartDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtStartDate;

        /// <summary>
        /// txtEndDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEndDate;

        /// <summary>
        /// txtReason control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtReason;

        /// <summary>
        /// fuMedicalCert control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload fuMedicalCert;

        /// <summary>
        /// btnSubmit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSubmit;

        /// <summary>
        /// btnClear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnClear;

        /// <summary>
        /// gvMyLeaveRequests control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvMyLeaveRequests;
    }
}
