//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.Leave
{
    public partial class SupervisorLeaveApproval
    {
        /// <summary>
        /// pnlMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// pnlNoSubordinates control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoSubordinates;

        /// <summary>
        /// pnlMainContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMainContent;

        /// <summary>
        /// lblTotalSubordinates control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalSubordinates;

        /// <summary>
        /// lblPendingRequests control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPendingRequests;

        /// <summary>
        /// lblApprovedThisYear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblApprovedThisYear;

        /// <summary>
        /// ddlStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;

        /// <summary>
        /// ddlYear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;

        /// <summary>
        /// txtSearchEmployee control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearchEmployee;

        /// <summary>
        /// btnSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;

        /// <summary>
        /// gvLeaveRequests control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvLeaveRequests;

        /// <summary>
        /// txtRejectReason control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRejectReason;

        /// <summary>
        /// hdnRejectRequestId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnRejectRequestId;

        /// <summary>
        /// btnConfirmReject control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConfirmReject;

        /// <summary>
        /// btnPrevMonth control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnPrevMonth;

        /// <summary>
        /// lblCurrentMonth control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCurrentMonth;

        /// <summary>
        /// btnNextMonth control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnNextMonth;

        /// <summary>
        /// hdnCalendarYear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnCalendarYear;

        /// <summary>
        /// hdnCalendarMonth control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnCalendarMonth;

        /// <summary>
        /// litCalendarDays control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCalendarDays;

        /// <summary>
        /// hdnCalendarLeaveData control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnCalendarLeaveData;
    }
}
