//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin
{
    public partial class AffiliateManagement
    {
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Label lblTotalAffiliates;
        protected global::System.Web.UI.WebControls.Label lblPendingCommissions;
        protected global::System.Web.UI.WebControls.Label lblPendingAmount;
        protected global::System.Web.UI.WebControls.Label lblTotalPaidAmount;
        protected global::System.Web.UI.WebControls.Button btnTabMembers;
        protected global::System.Web.UI.WebControls.Button btnTabCommissions;
        protected global::System.Web.UI.WebControls.Button btnTabCreatePayment;
        protected global::System.Web.UI.WebControls.Button btnTabHistory;
        protected global::System.Web.UI.WebControls.HiddenField hdnActiveTab;

        // Tab 1: Members
        protected global::System.Web.UI.WebControls.Panel pnlMembers;
        protected global::System.Web.UI.WebControls.TextBox txtSearchMember;
        protected global::System.Web.UI.WebControls.Button btnSearchMember;
        protected global::System.Web.UI.WebControls.GridView gvMembers;

        // Tab 2: Commissions
        protected global::System.Web.UI.WebControls.Panel pnlCommissions;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterAffiliate;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterStatus;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterYear;
        protected global::System.Web.UI.WebControls.GridView gvCommissions;

        // Tab 3: Create Payment
        protected global::System.Web.UI.WebControls.Panel pnlCreatePayment;
        protected global::System.Web.UI.WebControls.TextBox txtPaymentDate;
        protected global::System.Web.UI.WebControls.DropDownList ddlPaymentMethod;
        protected global::System.Web.UI.WebControls.DropDownList ddlSelectAffiliate;
        protected global::System.Web.UI.WebControls.Panel pnlPendingToPay;
        protected global::System.Web.UI.WebControls.Label lblSelectedAffiliate;
        protected global::System.Web.UI.WebControls.Label lblPaymentCount;
        protected global::System.Web.UI.WebControls.Label lblPaymentTotal;
        protected global::System.Web.UI.WebControls.GridView gvPendingPayments;
        protected global::System.Web.UI.WebControls.Button btnCreatePaymentVoucher;

        // Tab 4: History
        protected global::System.Web.UI.WebControls.Panel pnlHistory;
        protected global::System.Web.UI.WebControls.DropDownList ddlHistoryAffiliate;
        protected global::System.Web.UI.WebControls.DropDownList ddlHistoryYear;
        protected global::System.Web.UI.WebControls.GridView gvHistory;
    }
}
