//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin
{
    public partial class Vendor
    {
        /// <summary>
        /// pnlSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSearch;

        /// <summary>
        /// txtSearchTax control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearchTax;

        /// <summary>
        /// txtSearchName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearchName;

        /// <summary>
        /// ddlSearchGroup control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlSearchGroup;

        /// <summary>
        /// btnSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;

        /// <summary>
        /// btnClearSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnClearSearch;

        /// <summary>
        /// btnNewVendor control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnNewVendor;

        /// <summary>
        /// pnlVendorList control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlVendorList;

        /// <summary>
        /// gvVendors control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvVendors;

        /// <summary>
        /// pnlVendorForm control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlVendorForm;

        /// <summary>
        /// lblFormTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblFormTitle;

        /// <summary>
        /// txtTaxID control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTaxID;

        /// <summary>
        /// ddlVendorType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlVendorType;

        /// <summary>
        /// txtVendorName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtVendorName;

        /// <summary>
        /// txtBranchNumber control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBranchNumber;

        /// <summary>
        /// txtPhone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPhone;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// txtContactPerson control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtContactPerson;

        /// <summary>
        /// ddlVendorGroup control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlVendorGroup;

        /// <summary>
        /// txtAddress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAddress;

        /// <summary>
        /// txtAddress1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAddress1;

        /// <summary>
        /// txtPostalCode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPostalCode;

        /// <summary>
        /// btnSearchPostal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSearchPostal;

        /// <summary>
        /// btnClearPostal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnClearPostal;

        /// <summary>
        /// ddlProvince control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlProvince;

        /// <summary>
        /// ddlDistrict control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlDistrict;

        /// <summary>
        /// ddlSubDistrict control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlSubDistrict;

        /// <summary>
        /// txtRemark control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRemark;

        /// <summary>
        /// btnSave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSave;

        /// <summary>
        /// btnCancel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCancel;

        /// <summary>
        /// hfVendorID control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfVendorID;
    }
}
