//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin
{
    public partial class WebAnalytics
    {
        /// <summary>
        /// txtStartDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtStartDate;

        /// <summary>
        /// txtEndDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEndDate;

        /// <summary>
        /// ddlDateRange control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlDateRange;

        /// <summary>
        /// ddlUserType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlUserType;

        /// <summary>
        /// btnApplyFilter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnApplyFilter;

        /// <summary>
        /// lblTotalVisits control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalVisits;

        /// <summary>
        /// lblUniqueVisitors control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUniqueVisitors;

        /// <summary>
        /// lblTodayVisits control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTodayVisits;

        /// <summary>
        /// lblWeeklyVisits control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblWeeklyVisits;

        /// <summary>
        /// lblMonthlyVisits control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMonthlyVisits;

        /// <summary>
        /// lblErrorCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblErrorCount;

        /// <summary>
        /// lblStaffVisits control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStaffVisits;

        /// <summary>
        /// lblStaffPercent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStaffPercent;

        /// <summary>
        /// lblStaffUnique control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStaffUnique;

        /// <summary>
        /// lblCustomerVisits control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCustomerVisits;

        /// <summary>
        /// lblCustomerPercent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCustomerPercent;

        /// <summary>
        /// lblCustomerUnique control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCustomerUnique;

        /// <summary>
        /// btnTabOverview control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnTabOverview;

        /// <summary>
        /// btnTabBrowser control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnTabBrowser;

        /// <summary>
        /// btnTabTime control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnTabTime;

        /// <summary>
        /// btnTabVisitors control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnTabVisitors;

        /// <summary>
        /// btnTabActivity control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnTabActivity;

        /// <summary>
        /// btnTabErrors control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnTabErrors;

        /// <summary>
        /// btnTabAccessLog control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnTabAccessLog;

        /// <summary>
        /// hdnActiveTab control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnActiveTab;

        /// <summary>
        /// pnlOverview control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlOverview;

        /// <summary>
        /// gvDailyTrend control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvDailyTrend;

        /// <summary>
        /// gvDayOfWeek control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvDayOfWeek;

        /// <summary>
        /// pnlBrowser control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlBrowser;

        /// <summary>
        /// gvBrowser control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvBrowser;

        /// <summary>
        /// pnlTime control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlTime;

        /// <summary>
        /// gvHourly control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvHourly;

        /// <summary>
        /// gvMonthly control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvMonthly;

        /// <summary>
        /// pnlVisitors control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlVisitors;

        /// <summary>
        /// gvNewVsReturning control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvNewVsReturning;

        /// <summary>
        /// gvTopVisitors control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvTopVisitors;

        /// <summary>
        /// pnlActivity control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlActivity;

        /// <summary>
        /// gvActiveUsers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvActiveUsers;

        /// <summary>
        /// gvActionSummary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvActionSummary;

        /// <summary>
        /// pnlErrors control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlErrors;

        /// <summary>
        /// gvLogsByCategory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvLogsByCategory;

        /// <summary>
        /// gvLogsByLevel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvLogsByLevel;

        /// <summary>
        /// gvRecentErrors control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvRecentErrors;

        /// <summary>
        /// pnlAccessLog control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlAccessLog;

        /// <summary>
        /// lblAccessLogCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAccessLogCount;

        /// <summary>
        /// gvAccessLog control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvAccessLog;
    }
}
