<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>TakeTime.ApiGateway</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="Yarp.ReverseProxy" Version="2.1.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.2.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\TakeTime.Core\TakeTime.Core.csproj" />
    <ProjectReference Include="..\..\MultiTenancy\TakeTime.MultiTenancy\TakeTime.MultiTenancy.csproj" />
    <ProjectReference Include="..\..\Identity\TakeTime.Identity\TakeTime.Identity.csproj" />
    <ProjectReference Include="..\..\Infrastructure\TakeTime.Infrastructure\TakeTime.Infrastructure.csproj" />
  </ItemGroup>

</Project>
