//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Payment
{


    public partial class Card
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// hfToken control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfToken;

        /// <summary>
        /// litTestBand control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTestBand;

        /// <summary>
        /// litTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTitle;

        /// <summary>
        /// litDesc control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litDesc;

        /// <summary>
        /// litAmount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAmount;

        /// <summary>
        /// litHoldNote control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litHoldNote;

        /// <summary>
        /// litMsg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMsg;

        /// <summary>
        /// pnlForm control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlForm;

        /// <summary>
        /// litButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litButton;

        /// <summary>
        /// btnServer control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnServer;

        /// <summary>
        /// pnlDone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlDone;
    }
}
