//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Payment
{


    public partial class Charge
    {

        /// <summary>
        /// litPaidHowName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPaidHowName;

        /// <summary>
        /// litMsg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMsg;

        /// <summary>
        /// txtAmount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAmount;

        /// <summary>
        /// txtNote control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNote;

        /// <summary>
        /// btnCharge control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCharge;

        /// <summary>
        /// pnlChargeResult control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlChargeResult;

        /// <summary>
        /// litQr control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litQr;

        /// <summary>
        /// litQrCap control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litQrCap;

        /// <summary>
        /// txtPayLink control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPayLink;

        /// <summary>
        /// pnlHoldSection control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlHoldSection;

        /// <summary>
        /// txtHoldRes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtHoldRes;

        /// <summary>
        /// txtHoldAmount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtHoldAmount;

        /// <summary>
        /// ddlHoldMethod control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlHoldMethod;

        /// <summary>
        /// btnHold control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnHold;

        /// <summary>
        /// pnlHoldResult control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlHoldResult;

        /// <summary>
        /// txtHoldLink control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtHoldLink;

        /// <summary>
        /// gvToday control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvToday;
    }
}
