//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Payment
{


    public partial class GatewayTest
    {

        /// <summary>
        /// litMsg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMsg;

        /// <summary>
        /// litProvider control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litProvider;

        /// <summary>
        /// litMode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMode;

        /// <summary>
        /// pnlLiveGuard control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlLiveGuard;

        /// <summary>
        /// chkLiveOk control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkLiveOk;

        /// <summary>
        /// txtAmount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAmount;

        /// <summary>
        /// btnTestQr control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnTestQr;

        /// <summary>
        /// btnTestCard control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnTestCard;

        /// <summary>
        /// btnTestHold control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnTestHold;

        /// <summary>
        /// btnConn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConn;

        /// <summary>
        /// pnlResult control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlResult;

        /// <summary>
        /// litQr control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litQr;

        /// <summary>
        /// txtLink control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLink;

        /// <summary>
        /// pnlRaw control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlRaw;

        /// <summary>
        /// litRaw control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRaw;

        /// <summary>
        /// gvTest control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvTest;
    }
}
