//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Payment
{


    public partial class Pay
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// pnlError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlError;

        /// <summary>
        /// litError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litError;

        /// <summary>
        /// pnlMain control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMain;

        /// <summary>
        /// litItem control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litItem;

        /// <summary>
        /// phCustomer control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phCustomer;

        /// <summary>
        /// litCustomer control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCustomer;

        /// <summary>
        /// phSurcharge control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phSurcharge;

        /// <summary>
        /// litBase control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litBase;

        /// <summary>
        /// litSurcharge control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSurcharge;

        /// <summary>
        /// litAmount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAmount;

        /// <summary>
        /// pnlMethods control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMethods;

        /// <summary>
        /// rblMethod control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RadioButtonList rblMethod;

        /// <summary>
        /// btnContinue control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnContinue;

        /// <summary>
        /// pnlManual control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlManual;

        /// <summary>
        /// litManualQr control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litManualQr;

        /// <summary>
        /// litBank control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litBank;

        /// <summary>
        /// litManualNote control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litManualNote;

        /// <summary>
        /// fuSlip control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload fuSlip;

        /// <summary>
        /// btnManualConfirm control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnManualConfirm;

        /// <summary>
        /// btnManualBack control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnManualBack;

        /// <summary>
        /// pnlGateway control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlGateway;

        /// <summary>
        /// litGwInfo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litGwInfo;

        /// <summary>
        /// phGwLink control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phGwLink;

        /// <summary>
        /// lnkPay control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkPay;

        /// <summary>
        /// phGwQr control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phGwQr;

        /// <summary>
        /// litGwQr control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litGwQr;

        /// <summary>
        /// litRef control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRef;

        /// <summary>
        /// btnCheck control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCheck;

        /// <summary>
        /// btnGwBack control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnGwBack;

        /// <summary>
        /// pnlDone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlDone;

        /// <summary>
        /// litDone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litDone;

        /// <summary>
        /// lnkBackHome control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkBackHome;
    }
}
