//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Payment
{


    public partial class PayResult
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// pnlBox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlBox;

        /// <summary>
        /// litIcon control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litIcon;

        /// <summary>
        /// litTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTitle;

        /// <summary>
        /// litDetail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litDetail;

        /// <summary>
        /// litRef control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRef;

        /// <summary>
        /// btnRecheck control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnRecheck;

        /// <summary>
        /// lnkRetry control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkRetry;

        /// <summary>
        /// lnkHome control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkHome;
    }
}
