//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.Chat
{
    public partial class ChannelSettings
    {
        protected global::System.Web.UI.WebControls.HiddenField hfChannels;
    }
}
