//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.Chat
{

    public partial class ChatManagement
    {

        /// <summary>
        /// pnlUnreadBadge control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlUnreadBadge;

        /// <summary>
        /// lblUnreadCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUnreadCount;

        /// <summary>
        /// rptChatList control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptChatList;

        /// <summary>
        /// pnlNoChats control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoChats;

        /// <summary>
        /// pnlChatDetail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlChatDetail;

        /// <summary>
        /// lblChatGuestName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblChatGuestName;

        /// <summary>
        /// lblChatRoomName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblChatRoomName;

        /// <summary>
        /// lblChatPhone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblChatPhone;

        /// <summary>
        /// btnMarkResolved control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnMarkResolved;

        /// <summary>
        /// rptChatMessages control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptChatMessages;

        /// <summary>
        /// txtReply control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtReply;

        /// <summary>
        /// btnSendReply control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSendReply;

        /// <summary>
        /// pnlSelectChat control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSelectChat;

        /// <summary>
        /// hfSelectedChat control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfSelectedChat;

        /// <summary>
        /// btnLoadChat control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnLoadChat;
    }
}
