//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.Chat
{
    public partial class OmniChannelInbox
    {
        protected global::System.Web.UI.WebControls.HiddenField hfChannelsData;
        protected global::System.Web.UI.WebControls.HiddenField hfCannedData;
    }
}
