//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.HR
{
    public partial class EmployeeManagement
    {
        /// <summary>
        /// lblTotalEmployees control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalEmployees;

        /// <summary>
        /// lblNewEmployees control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNewEmployees;

        /// <summary>
        /// lblExpiringContracts control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblExpiringContracts;

        /// <summary>
        /// lblExpiringDocuments control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblExpiringDocuments;

        /// <summary>
        /// btnAddEmployee control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAddEmployee;

        /// <summary>
        /// txtSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        /// <summary>
        /// ddlDepartment control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlDepartment;

        /// <summary>
        /// ddlStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;

        /// <summary>
        /// btnSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;

        /// <summary>
        /// btnReset control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnReset;

        /// <summary>
        /// gvEmployees control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvEmployees;

        /// <summary>
        /// hdnEmployeeId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnEmployeeId;

        /// <summary>
        /// hdnEditMode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnEditMode;

        /// <summary>
        /// txtUsername control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtUsername;

        /// <summary>
        /// txtPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        /// <summary>
        /// txtFirstName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFirstName;

        /// <summary>
        /// txtLastName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLastName;

        /// <summary>
        /// ddlRole control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlRole;

        /// <summary>
        /// txtSalary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSalary;

        /// <summary>
        /// txtPosition control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPosition;

        /// <summary>
        /// btnSaveEmployee control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSaveEmployee;

        /// <summary>
        /// txtResignDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtResignDate;

        /// <summary>
        /// ddlResignType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlResignType;

        /// <summary>
        /// txtResignReason control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtResignReason;

        /// <summary>
        /// btnConfirmResign control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConfirmResign;

        /// <summary>
        /// pnlMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// imgSignature control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgSignature;

        /// <summary>
        /// fuSignature control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload fuSignature;

        /// <summary>
        /// btnUploadSignature control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnUploadSignature;

        /// <summary>
        /// btnDeleteSignature control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnDeleteSignature;

        /// <summary>
        /// txtIDCard control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtIDCard;

        /// <summary>
        /// txtBirthDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBirthDate;

        /// <summary>
        /// txtPhone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPhone;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// txtAddress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAddress;

        /// <summary>
        /// txtHireDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtHireDate;

        /// <summary>
        /// ddlBank control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlBank;

        /// <summary>
        /// txtBankAccountNumber control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBankAccountNumber;

        /// <summary>
        /// txtBankAccountName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBankAccountName;

        /// <summary>
        /// txtEmergencyContact control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmergencyContact;

        /// <summary>
        /// txtEmergencyPhone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmergencyPhone;
    }
}
