//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.HR
{
    public partial class EmployeeProfile
    {
        /// <summary>
        /// lblName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblName;

        /// <summary>
        /// lblPosition control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPosition;

        /// <summary>
        /// lblStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStatus;

        /// <summary>
        /// lblServiceYears control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblServiceYears;

        /// <summary>
        /// lblLeaveBalance control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblLeaveBalance;

        /// <summary>
        /// lblTrainingCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTrainingCount;

        /// <summary>
        /// lblEmployeeCode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEmployeeCode;

        /// <summary>
        /// lblFullNameTH control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblFullNameTH;

        /// <summary>
        /// lblFullNameEN control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblFullNameEN;

        /// <summary>
        /// lblIDCard control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblIDCard;

        /// <summary>
        /// lblBirthDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblBirthDate;

        /// <summary>
        /// lblPhone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPhone;

        /// <summary>
        /// lblEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEmail;

        /// <summary>
        /// lblAddress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAddress;

        /// <summary>
        /// lblEmergencyContact control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEmergencyContact;

        /// <summary>
        /// lblEmergencyPhone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEmergencyPhone;

        /// <summary>
        /// lblStartDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStartDate;

        /// <summary>
        /// lblDepartment control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblDepartment;

        /// <summary>
        /// lblCurrentPosition control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCurrentPosition;

        /// <summary>
        /// lblContractType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblContractType;

        /// <summary>
        /// lblContractEnd control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblContractEnd;

        /// <summary>
        /// gvEmploymentHistory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvEmploymentHistory;

        /// <summary>
        /// lblSalary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSalary;

        /// <summary>
        /// lblSalaryEffective control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSalaryEffective;

        /// <summary>
        /// gvSalaryHistory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvSalaryHistory;

        /// <summary>
        /// gvLeaveQuota control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvLeaveQuota;

        /// <summary>
        /// gvTraining control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvTraining;
    }
}
