//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.HR
{
    public partial class EmployeeManagement
    {
        /// <summary>
        /// lblTotalEmployees control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalEmployees;

        /// <summary>
        /// lblNewEmployees control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNewEmployees;

        /// <summary>
        /// lblExpiringContracts control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblExpiringContracts;

        /// <summary>
        /// lblExpiringDocuments control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblExpiringDocuments;

        /// <summary>
        /// txtSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        /// <summary>
        /// ddlDepartment control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlDepartment;

        /// <summary>
        /// btnSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;

        /// <summary>
        /// btnReset control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnReset;

        /// <summary>
        /// gvEmployees control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvEmployees;
    }
}
