//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.HR
{
    public partial class OTEntry
    {
        /// <summary>
        /// hdnActiveTab control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnActiveTab;

        /// <summary>
        /// pnlMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// lblApprovedHours control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblApprovedHours;

        /// <summary>
        /// lblPendingHours control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPendingHours;

        /// <summary>
        /// lblSubordinatePending control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSubordinatePending;

        /// <summary>
        /// pnlApprovalTab control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlApprovalTab;

        /// <summary>
        /// pnlSupervisorMode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSupervisorMode;

        /// <summary>
        /// ddlEmployee control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlEmployee;

        /// <summary>
        /// txtOTDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtOTDate;

        /// <summary>
        /// txtOTHours control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtOTHours;

        /// <summary>
        /// ddlOTRate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlOTRate;

        /// <summary>
        /// txtWorkDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtWorkDescription;

        /// <summary>
        /// txtNotes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNotes;

        /// <summary>
        /// btnSaveOT control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSaveOT;

        /// <summary>
        /// btnClear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnClear;

        /// <summary>
        /// ddlMyMonth control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlMyMonth;

        /// <summary>
        /// ddlMyYear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlMyYear;

        /// <summary>
        /// gvMyOT control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvMyOT;

        /// <summary>
        /// ddlApprovalStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlApprovalStatus;

        /// <summary>
        /// ddlApprovalMonth control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlApprovalMonth;

        /// <summary>
        /// ddlApprovalYear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlApprovalYear;

        /// <summary>
        /// gvSubordinateOT control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvSubordinateOT;
    }
}
