//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.HR
{
    public partial class OTManagement
    {
        /// <summary>
        /// pnlMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// lblTotalEntries control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalEntries;

        /// <summary>
        /// lblPendingCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPendingCount;

        /// <summary>
        /// lblApprovedCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblApprovedCount;

        /// <summary>
        /// lblTotalHours control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalHours;

        /// <summary>
        /// ddlStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;

        /// <summary>
        /// ddlMonth control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlMonth;

        /// <summary>
        /// ddlYear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;

        /// <summary>
        /// ddlEmployee control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlEmployee;

        /// <summary>
        /// hdnEditId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnEditId;

        /// <summary>
        /// gvOTEntries control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvOTEntries;

        /// <summary>
        /// pnlEditForm control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlEditForm;

        /// <summary>
        /// lblEditEmployee control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEditEmployee;

        /// <summary>
        /// txtEditDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEditDate;

        /// <summary>
        /// txtEditHours control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEditHours;

        /// <summary>
        /// ddlEditRate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlEditRate;

        /// <summary>
        /// txtEditDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEditDescription;

        /// <summary>
        /// ddlEditStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlEditStatus;

        /// <summary>
        /// txtEditNotes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEditNotes;

        /// <summary>
        /// btnSaveEdit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSaveEdit;
    }
}
