//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.HR
{
    public partial class SupervisorManagement
    {
        /// <summary>
        /// pnlMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// lblTotalRelationships control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalRelationships;

        /// <summary>
        /// lblEmployeesWithSupervisor control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEmployeesWithSupervisor;

        /// <summary>
        /// lblTotalSupervisors control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalSupervisors;

        /// <summary>
        /// txtSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        /// <summary>
        /// btnSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;

        /// <summary>
        /// btnReset control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnReset;

        /// <summary>
        /// gvRelationships control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvRelationships;

        /// <summary>
        /// ddlEmployee control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlEmployee;

        /// <summary>
        /// ddlSupervisor control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlSupervisor;

        /// <summary>
        /// chkIsPrimary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkIsPrimary;

        /// <summary>
        /// chkCanApproveLeave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkCanApproveLeave;

        /// <summary>
        /// chkCanViewSalary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkCanViewSalary;

        /// <summary>
        /// txtNotes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNotes;

        /// <summary>
        /// btnSaveRelationship control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSaveRelationship;
    }
}
