//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra
{
    public partial class ActivitiesPublic
    {
        /// <summary>
        /// litActivities control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litActivities;
    }
}
