//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra
{


    public partial class PostponeList
    {

        /// <summary>
        /// GridView1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView GridView1;

        protected global::System.Web.UI.WebControls.Label lblPostponeCount;

        protected global::System.Web.UI.WebControls.Button btnRefresh;

        protected global::System.Web.UI.WebControls.HiddenField hdnCancelReservationId;

        protected global::System.Web.UI.WebControls.HiddenField hdnCancelReason;

        protected global::System.Web.UI.WebControls.Button btnCancelWithReason;

        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        protected global::System.Web.UI.WebControls.Literal litMessage;

        protected global::System.Web.UI.WebControls.Label lblSummaryCount;

        protected global::System.Web.UI.WebControls.Label lblTotalHeld;

        protected global::System.Web.UI.WebControls.Label lblExpiringCount;

        protected global::System.Web.UI.WebControls.Label lblExpiredCount;

        protected global::System.Web.UI.WebControls.Label lblOldestDays;

        protected global::System.Web.UI.WebControls.Literal litPolicy;

        protected global::System.Web.UI.WebControls.Panel pnlSearch;

        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        protected global::System.Web.UI.WebControls.DropDownList ddlFilter;

        protected global::System.Web.UI.WebControls.Button btnSearch;

        protected global::System.Web.UI.WebControls.Button btnClearSearch;

        protected global::System.Web.UI.WebControls.Label lblShown;
    }
}
