//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra
{


    public partial class PostponeList
    {

        /// <summary>
        /// GridView1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView GridView1;

        protected global::System.Web.UI.WebControls.Label lblPostponeCount;

        protected global::System.Web.UI.WebControls.Button btnRefresh;

        protected global::System.Web.UI.WebControls.HiddenField hdnCancelReservationId;

        protected global::System.Web.UI.WebControls.HiddenField hdnCancelReason;

        protected global::System.Web.UI.WebControls.Button btnCancelWithReason;
    }
}
