//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra
{
    public partial class ReservationList
    {
        /// <summary>
        /// btnStatAll control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnStatAll;

        /// <summary>
        /// lblStatAll control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStatAll;

        /// <summary>
        /// btnStatToday control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnStatToday;

        /// <summary>
        /// lblStatToday control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStatToday;

        /// <summary>
        /// btnStatDeposit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnStatDeposit;

        /// <summary>
        /// lblStatDeposit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStatDeposit;

        /// <summary>
        /// btnStatCheckin control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnStatCheckin;

        /// <summary>
        /// lblStatCheckin control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStatCheckin;

        /// <summary>
        /// btnStatCheckout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnStatCheckout;

        /// <summary>
        /// lblStatCheckout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStatCheckout;

        /// <summary>
        /// btnStatComplete control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnStatComplete;

        /// <summary>
        /// lblStatComplete control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStatComplete;

        /// <summary>
        /// btnStatCancel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnStatCancel;

        /// <summary>
        /// lblStatCancel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStatCancel;

        /// <summary>
        /// txtSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        /// <summary>
        /// ddlStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;

        /// <summary>
        /// txtDateFrom control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDateFrom;

        /// <summary>
        /// txtDateTo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDateTo;

        /// <summary>
        /// ddlSortBy control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlSortBy;

        /// <summary>
        /// btnSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;

        /// <summary>
        /// btnClear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnClear;

        /// <summary>
        /// btnExport control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnExport;

        /// <summary>
        /// lblResultCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblResultCount;

        /// <summary>
        /// lblTotalAmount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalAmount;

        /// <summary>
        /// lblTotalDeposit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalDeposit;

        /// <summary>
        /// lblTotalRemain control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalRemain;

        /// <summary>
        /// gvReservations control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvReservations;

        /// <summary>
        /// btnPrevPage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnPrevPage;

        /// <summary>
        /// lblCurrentPage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCurrentPage;

        /// <summary>
        /// lblTotalPages control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalPages;

        /// <summary>
        /// btnNextPage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnNextPage;
    }
}
