//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.CRM
{
    public partial class GuestProfile
    {
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl alertBox;
        protected global::System.Web.UI.WebControls.Label lblAlertMessage;
        protected global::System.Web.UI.WebControls.TextBox txtSearchPhone;
        protected global::System.Web.UI.WebControls.TextBox txtSearchName;
        protected global::System.Web.UI.WebControls.TextBox txtSearchEmail;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Panel pnlNotFound;
        protected global::System.Web.UI.WebControls.Panel pnlProfile;
        protected global::System.Web.UI.WebControls.Label lblInitials;
        protected global::System.Web.UI.WebControls.Label lblCustomerName;
        protected global::System.Web.UI.WebControls.Panel pnlTierBadge;
        protected global::System.Web.UI.WebControls.Label lblTierName;
        protected global::System.Web.UI.WebControls.Panel pnlVipBadge;
        protected global::System.Web.UI.WebControls.Label lblPhone;
        protected global::System.Web.UI.WebControls.Label lblEmail;
        protected global::System.Web.UI.WebControls.Label lblMemberSince;
        protected global::System.Web.UI.WebControls.Label lblPoints;
        protected global::System.Web.UI.WebControls.Label lblTotalBookings;
        protected global::System.Web.UI.WebControls.Label lblLifetimeValue;
        protected global::System.Web.UI.WebControls.Label lblAvgRating;
        protected global::System.Web.UI.WebControls.Label lblFullName;
        protected global::System.Web.UI.WebControls.Label lblNickname;
        protected global::System.Web.UI.WebControls.Label lblIDNumber;
        protected global::System.Web.UI.WebControls.Label lblAddress;
        protected global::System.Web.UI.WebControls.Label lblSegment;
        protected global::System.Web.UI.WebControls.Label lblCurrentTier;
        protected global::System.Web.UI.WebControls.Label lblCurrentPoints;
        protected global::System.Web.UI.WebControls.Label lblNextTier;
        protected global::System.Web.UI.WebControls.Label lblPointsToNext;
        protected global::System.Web.UI.WebControls.Label lblMultiplier;
        protected global::System.Web.UI.WebControls.Label lblDiscountPercent;
        protected global::System.Web.UI.WebControls.Panel pnlSpecialDates;
        protected global::System.Web.UI.WebControls.Label lblNoSpecialDates;
        protected global::System.Web.UI.WebControls.Repeater rptBookings;
        protected global::System.Web.UI.WebControls.Label lblNoBookings;
        protected global::System.Web.UI.WebControls.Repeater rptReviews;
        protected global::System.Web.UI.WebControls.Label lblNoReviews;
        protected global::System.Web.UI.WebControls.Panel pnlPreferences;
        protected global::System.Web.UI.WebControls.Label lblNoPreferences;
        protected global::System.Web.UI.WebControls.Repeater rptNotes;
        protected global::System.Web.UI.WebControls.Label lblNoNotes;
        protected global::System.Web.UI.WebControls.Button btnAddNote;
        protected global::System.Web.UI.WebControls.Button btnEditProfile;
        protected global::System.Web.UI.WebControls.Button btnViewFullHistory;
        protected global::System.Web.UI.WebControls.Button btnManagePoints;
    }
}
