//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.CRM
{
    public partial class LoyaltyDashboard
    {
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl alertBox;
        protected global::System.Web.UI.WebControls.Label lblAlertMessage;
        protected global::System.Web.UI.WebControls.Label lblTotalMembers;
        protected global::System.Web.UI.WebControls.Label lblMembersChange;
        protected global::System.Web.UI.WebControls.Label lblActiveMembers;
        protected global::System.Web.UI.WebControls.Label lblActivePercent;
        protected global::System.Web.UI.WebControls.Label lblPointsEarned;
        protected global::System.Web.UI.WebControls.Label lblPointsEarnedChange;
        protected global::System.Web.UI.WebControls.Label lblPointsRedeemed;
        protected global::System.Web.UI.WebControls.Label lblRedemptionRate;
        protected global::System.Web.UI.WebControls.Label lblTotalMembersBreakdown;
        protected global::System.Web.UI.WebControls.Repeater rptTierBreakdown;
        protected global::System.Web.UI.WebControls.Repeater rptRecentTransactions;
        protected global::System.Web.UI.WebControls.Label lblNoTransactions;
        protected global::System.Web.UI.WebControls.Button btnTabRewards;
        protected global::System.Web.UI.WebControls.Button btnTabReports;
        protected global::System.Web.UI.WebControls.Panel pnlRewards;
        protected global::System.Web.UI.WebControls.Button btnAddReward;
        protected global::System.Web.UI.WebControls.Repeater rptRewards;
        protected global::System.Web.UI.WebControls.Label lblNoRewards;
        protected global::System.Web.UI.WebControls.Panel pnlReports;
        protected global::System.Web.UI.WebControls.GridView gvTierPerformance;
        protected global::System.Web.UI.WebControls.GridView gvMonthlyTrends;
        protected global::System.Web.UI.WebControls.Panel pnlRewardModal;
        protected global::System.Web.UI.WebControls.Label lblModalTitle;
        protected global::System.Web.UI.WebControls.TextBox txtRewardName;
        protected global::System.Web.UI.WebControls.TextBox txtRewardNameEN;
        protected global::System.Web.UI.WebControls.TextBox txtRewardDescription;
        protected global::System.Web.UI.WebControls.DropDownList ddlRewardCategory;
        protected global::System.Web.UI.WebControls.TextBox txtPointsRequired;
        protected global::System.Web.UI.WebControls.TextBox txtAvailableQuantity;
        protected global::System.Web.UI.WebControls.TextBox txtValidFrom;
        protected global::System.Web.UI.WebControls.TextBox txtValidTo;
        protected global::System.Web.UI.WebControls.Button btnSaveReward;
        protected global::System.Web.UI.WebControls.Button btnCancelReward;
        protected global::System.Web.UI.WebControls.HiddenField hfEditingRewardId;
    }
}
