//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.CRM
{
    public partial class MemberHub
    {
        protected global::System.Web.UI.WebControls.Panel pnlMsg;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divMsg;
        protected global::System.Web.UI.WebControls.Literal litMsg;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Literal litSearchResults;
        protected global::System.Web.UI.WebControls.Panel pnlMember;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divAvatar;
        protected global::System.Web.UI.WebControls.Literal litInitial;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spanTier;
        protected global::System.Web.UI.WebControls.Literal litTier;
        protected global::System.Web.UI.WebControls.Literal litName;
        protected global::System.Web.UI.WebControls.Literal litPhone;
        protected global::System.Web.UI.WebControls.Literal litSince;
        protected global::System.Web.UI.WebControls.Literal litExpiry;
        protected global::System.Web.UI.WebControls.Literal litPoints;
        protected global::System.Web.UI.WebControls.Literal litPinState;
        protected global::System.Web.UI.WebControls.Button btnResetPin;
        protected global::System.Web.UI.WebControls.TextBox txtExpiry;
        protected global::System.Web.UI.WebControls.Button btnSetExpiry;
        protected global::System.Web.UI.WebControls.DropDownList ddlEnrollTier;
        protected global::System.Web.UI.WebControls.TextBox txtEnrollFee;
        protected global::System.Web.UI.WebControls.DropDownList ddlPaidHow;
        protected global::System.Web.UI.WebControls.Button btnEnroll;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divEnrollHint;
        protected global::System.Web.UI.WebControls.Literal litVoucherMatrix;
        protected global::System.Web.UI.WebControls.Button btnSaveMatrix;
        protected global::System.Web.UI.WebControls.Literal litUsage;
        protected global::System.Web.UI.WebControls.Literal litPayments;
        protected global::System.Web.UI.WebControls.Panel pnlTierConfig;
        protected global::System.Web.UI.WebControls.Literal litTierFees;
        protected global::System.Web.UI.WebControls.Button btnSaveTierFees;
    }
}
