//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.CRM
{
    public partial class MembershipManagement
    {
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl alertBox;
        protected global::System.Web.UI.WebControls.Label lblAlert;
        protected global::System.Web.UI.WebControls.Label lblTotalMembers;
        protected global::System.Web.UI.WebControls.Label lblTotalAvailable;
        protected global::System.Web.UI.WebControls.Label lblPendingRedemptions;
        protected global::System.Web.UI.WebControls.Label lblRedeemedMonth;
        protected global::System.Web.UI.WebControls.Button btnTabMembers;
        protected global::System.Web.UI.WebControls.Button btnTabRedemptions;
        protected global::System.Web.UI.WebControls.Panel pnlMembers;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlTierFilter;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.GridView gvMembers;
        protected global::System.Web.UI.WebControls.Label lblNoMembers;
        protected global::System.Web.UI.WebControls.Panel pnlRedemptions;
        protected global::System.Web.UI.WebControls.DropDownList ddlRedemptionStatus;
        protected global::System.Web.UI.WebControls.GridView gvRedemptions;
        protected global::System.Web.UI.WebControls.Label lblNoRedemptions;
        protected global::System.Web.UI.WebControls.Panel pnlMemberModal;
        protected global::System.Web.UI.WebControls.Label lblMemberName;
        protected global::System.Web.UI.WebControls.Button btnCloseModal;
        protected global::System.Web.UI.WebControls.Label lblDetailTier;
        protected global::System.Web.UI.WebControls.Label lblDetailYearly;
        protected global::System.Web.UI.WebControls.Label lblDetailAvailable;
        protected global::System.Web.UI.WebControls.TextBox txtAdjustPoints;
        protected global::System.Web.UI.WebControls.TextBox txtAdjustReason;
        protected global::System.Web.UI.WebControls.CheckBox chkAffectTier;
        protected global::System.Web.UI.WebControls.Button btnAdjust;
        protected global::System.Web.UI.WebControls.GridView gvMemberHistory;
        protected global::System.Web.UI.WebControls.HiddenField hfSelectedPhone;
    }
}
