//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.CRM
{
    public partial class MemberVouchers
    {
        protected global::System.Web.UI.WebControls.Panel pnlMsg;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divMsg;
        protected global::System.Web.UI.WebControls.Literal litMsg;
        protected global::System.Web.UI.WebControls.TextBox txtRedeemCode;
        protected global::System.Web.UI.WebControls.TextBox txtRedeemNote;
        protected global::System.Web.UI.WebControls.Button btnRedeem;
        protected global::System.Web.UI.WebControls.Literal litDiscRows;
        protected global::System.Web.UI.WebControls.Button btnSaveDisc;
        protected global::System.Web.UI.WebControls.Literal litTplRows;
        protected global::System.Web.UI.WebControls.HiddenField hfTplId;
        protected global::System.Web.UI.WebControls.TextBox txtTplName;
        protected global::System.Web.UI.WebControls.TextBox txtTplDesc;
        protected global::System.Web.UI.WebControls.TextBox txtTplPrefix;
        protected global::System.Web.UI.WebControls.TextBox txtTplDays;
        protected global::System.Web.UI.WebControls.TextBox txtTplWindow;
        protected global::System.Web.UI.WebControls.CheckBox chkTplActive;
        protected global::System.Web.UI.WebControls.Button btnSaveTpl;
        protected global::System.Web.UI.WebControls.DropDownList ddlIssueTpl;
        protected global::System.Web.UI.WebControls.TextBox txtIssuePhone;
        protected global::System.Web.UI.WebControls.Button btnIssueOne;
        protected global::System.Web.UI.WebControls.DropDownList ddlIssueTier;
        protected global::System.Web.UI.WebControls.Button btnIssueTier;
        protected global::System.Web.UI.WebControls.Literal litHistory;
    }
}
