//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.CRM
{
    public partial class RedemptionTerminal
    {
        protected global::System.Web.UI.WebControls.Repeater rptRewards;
        protected global::System.Web.UI.WebControls.Label lblNoRewards;
    }
}
