//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.CRM
{
    public partial class ReviewManagement
    {
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl alertBox;
        protected global::System.Web.UI.WebControls.Label lblAlertMessage;
        protected global::System.Web.UI.WebControls.Label lblTotalReviews;
        protected global::System.Web.UI.WebControls.Label lblAvgRating;
        protected global::System.Web.UI.WebControls.Label lblPending;
        protected global::System.Web.UI.WebControls.Label lblApproved;
        protected global::System.Web.UI.WebControls.Label lblResponseRate;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatusFilter;
        protected global::System.Web.UI.WebControls.DropDownList ddlRatingFilter;
        protected global::System.Web.UI.WebControls.TextBox txtSearchCustomer;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Repeater rptReviews;
        protected global::System.Web.UI.WebControls.Label lblNoReviews;
    }
}
