using System;
using System.Collections.Generic;

namespace Take_Time_BangPhra.Integration
{
    // ──────────────────────────────────────────────
    // Authentication: ใช้ X-Api-Key header (ตรงตาม Nexaacc ApiKeyMiddleware.cs)
    // ไม่ต้องมี login/refresh models — API Key ส่งผ่าน header ทุก request
    // ──────────────────────────────────────────────

    // ──────────────────────────────────────────────
    // Generic API Response Wrapper (ตรงตาม Nexaacc Common.cs)
    // ──────────────────────────────────────────────

    public class ApiResponse<T>
    {
        public bool success { get; set; }
        public string message { get; set; }
        public T data { get; set; }
        public List<string> errors { get; set; }
    }

    // ──────────────────────────────────────────────
    // Journal Entries (ตรงตาม Nexaacc AccountingDtos.cs)
    // ──────────────────────────────────────────────

    public class CreateJournalEntryRequest
    {
        public DateTime EntryDate { get; set; }
        public int JournalType { get; set; }  // 0=General, 1=Sales, 2=Purchase, 3=CashReceipts, 4=CashPayments
        public string Description { get; set; }
        public string Reference { get; set; }
        public List<JournalEntryLineRequest> Lines { get; set; }
    }

    public class JournalEntryLineRequest
    {
        public Guid AccountId { get; set; }
        public decimal DebitAmount { get; set; }
        public decimal CreditAmount { get; set; }
        public string Description { get; set; }
    }

    public class JournalEntryResponse
    {
        public Guid Id { get; set; }
        public string EntryNumber { get; set; }
        public DateTime EntryDate { get; set; }
        public int JournalType { get; set; }
        public string Description { get; set; }
        public string Reference { get; set; }
        public int Status { get; set; }  // 0=Draft, 1=Posted, 2=Voided
        public bool IsAutoGenerated { get; set; }
        public decimal TotalDebit { get; set; }
        public decimal TotalCredit { get; set; }
        public List<JournalEntryLineResponse> Lines { get; set; }
        public DateTime CreatedAt { get; set; }
    }

    public class JournalEntryLineResponse
    {
        public Guid Id { get; set; }
        public Guid AccountId { get; set; }
        public string AccountCode { get; set; }
        public string AccountName { get; set; }
        public decimal DebitAmount { get; set; }
        public decimal CreditAmount { get; set; }
        public string Description { get; set; }
        public int LineOrder { get; set; }
    }

    // ──────────────────────────────────────────────
    // Chart of Accounts (ตรงตาม Nexaacc AccountingDtos.cs)
    // ──────────────────────────────────────────────

    public class AccountResponse
    {
        public Guid Id { get; set; }
        public string AccountCode { get; set; }
        public string AccountName { get; set; }
        public string AccountNameEn { get; set; }
        public int AccountType { get; set; }  // 1=Asset, 2=Liability, 3=Equity, 4=Revenue, 5=Expense
        public Guid? ParentAccountId { get; set; }
        public int Level { get; set; }
        public bool IsActive { get; set; }
        public bool IsSystemAccount { get; set; }
        public string Description { get; set; }
    }

    // ──────────────────────────────────────────────
    // Documents (ตรงตาม Nexaacc DocumentDtos.cs)
    // ──────────────────────────────────────────────

    public class CreateDocumentRequest
    {
        public int DocumentType { get; set; }
        public DateTime DocumentDate { get; set; }
        public DateTime? DueDate { get; set; }
        public Guid? ContactId { get; set; }
        public string Reference { get; set; }
        public string Notes { get; set; }
        public List<DocumentLineRequest> Lines { get; set; }
    }

    public class DocumentLineRequest
    {
        public string Description { get; set; }
        public decimal Quantity { get; set; }
        public string Unit { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal DiscountPercent { get; set; }
        public decimal VatRate { get; set; }
        public decimal WithholdingTaxRate { get; set; }
        public Guid? AccountId { get; set; }
    }

    public class DocumentResponse
    {
        public Guid Id { get; set; }
        public string DocumentNumber { get; set; }
        public int DocumentType { get; set; }
        public int Status { get; set; }
        public DateTime DocumentDate { get; set; }
        public DateTime? DueDate { get; set; }
        public decimal SubTotal { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal VatAmount { get; set; }
        public decimal WithholdingTaxAmount { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal PaidAmount { get; set; }
        public decimal BalanceDue { get; set; }
        public string Notes { get; set; }
        public DateTime CreatedAt { get; set; }
    }

    // ──────────────────────────────────────────────
    // Contacts (ตรงตาม Nexaacc DocumentDtos.cs)
    // ──────────────────────────────────────────────

    public class CreateContactRequest
    {
        public string Name { get; set; }
        public string TaxId { get; set; }
        public string BranchCode { get; set; }
        public int? ContactType { get; set; }  // 1=Individual, 2=JuristicPerson, 3=GovernmentAgency
        public bool IsCustomer { get; set; }
        public bool IsSupplier { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string ContactPerson { get; set; }
    }

    public class UpdateContactRequest
    {
        public string Name { get; set; }
        public string TaxId { get; set; }
        public string BranchCode { get; set; }
        public int? ContactType { get; set; }
        public bool? IsCustomer { get; set; }
        public bool? IsSupplier { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string ContactPerson { get; set; }
        public bool? IsActive { get; set; }
    }

    public class ContactResponse
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string TaxId { get; set; }
        public string BranchCode { get; set; }
        public int ContactType { get; set; }
        public bool IsCustomer { get; set; }
        public bool IsSupplier { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string ContactPerson { get; set; }
        public bool IsActive { get; set; }
    }

    // ──────────────────────────────────────────────
    // Payments (ตรงตาม Nexaacc DocumentDtos.cs)
    // ──────────────────────────────────────────────

    public class CreatePaymentRequest
    {
        public Guid DocumentId { get; set; }
        public DateTime PaymentDate { get; set; }
        public decimal Amount { get; set; }
        public string PaymentMethod { get; set; }
        public string Reference { get; set; }
        public Guid? BankAccountId { get; set; }
    }

    public class PaymentResponse
    {
        public Guid Id { get; set; }
        public Guid DocumentId { get; set; }
        public decimal Amount { get; set; }
        public string PaymentMethod { get; set; }
        public DateTime PaymentDate { get; set; }
    }

    // ──────────────────────────────────────────────
    // Products (ตรงตาม Nexaacc ProductDtos.cs)
    // ──────────────────────────────────────────────

    public class CreateProductRequest
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal SellingPrice { get; set; }
        public decimal CostPrice { get; set; }
        public string Unit { get; set; }
        public Guid? CategoryId { get; set; }
        public Guid? SalesAccountId { get; set; }
        public Guid? PurchaseAccountId { get; set; }
        public Guid? InventoryAccountId { get; set; }
        public bool TrackInventory { get; set; }
    }

    public class UpdateProductRequest
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal SellingPrice { get; set; }
        public decimal CostPrice { get; set; }
        public string Unit { get; set; }
    }

    public class ProductResponse
    {
        public Guid Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public decimal SellingPrice { get; set; }
        public decimal CostPrice { get; set; }
        public string Unit { get; set; }
        public decimal CurrentStock { get; set; }
    }

    // ──────────────────────────────────────────────
    // Stock (ตรงตาม Nexaacc ProductDtos.cs)
    // ──────────────────────────────────────────────

    public class StockAdjustmentRequest
    {
        public Guid ProductId { get; set; }
        public decimal Quantity { get; set; }
        public string Reason { get; set; }
        public string Reference { get; set; }
    }

    public class StockMovementResponse
    {
        public Guid Id { get; set; }
        public Guid ProductId { get; set; }
        public decimal Quantity { get; set; }
        public string Reason { get; set; }
        public DateTime CreatedDate { get; set; }
    }

    // ──────────────────────────────────────────────
    // Enums (ตรงตาม Nexaacc AllEnums.cs)
    // ──────────────────────────────────────────────

    public static class NexaaccJournalType
    {
        public const int General = 0;       // JV - สมุดรายวันทั่วไป
        public const int Sales = 1;         // SV - สมุดรายวันขาย
        public const int Purchase = 2;      // UV - สมุดรายวันซื้อ
        public const int CashReceipts = 3;  // RV - สมุดรายวันรับ
        public const int CashPayments = 4;  // PV - สมุดรายวันจ่าย
    }

    public static class NexaaccAccountType
    {
        public const int Asset = 1;
        public const int Liability = 2;
        public const int Equity = 3;
        public const int Revenue = 4;
        public const int Expense = 5;
    }

    /// <summary>
    /// Document Types ตรงตาม Nexaacc — เริ่มจาก 1 (ไม่ใช่ 0)
    /// </summary>
    public static class NexaaccDocumentType
    {
        // ฝั่งรายรับ
        public const int Quotation = 1;
        public const int Invoice = 2;
        public const int Receipt = 3;
        public const int TaxInvoice = 4;
        public const int DebitNote = 5;
        public const int CreditNote = 6;
        public const int DeliveryNote = 10;
        public const int BillingNote = 11;
        public const int ReceiptVoucher = 14;
        // ฝั่งรายจ่าย
        public const int PurchaseOrder = 7;
        public const int PurchaseRequisition = 12;
    }

    public static class NexaaccDocumentStatus
    {
        public const int Draft = 0;
        public const int WaitingApproval = 1;
        public const int Approved = 2;
        public const int Sent = 3;
        public const int PartiallyPaid = 4;
        public const int Paid = 5;
        public const int Voided = 6;
        public const int Overdue = 7;
        public const int Rejected = 8;
    }

    public static class NexaaccContactType
    {
        public const int Individual = 1;        // บุคคลธรรมดา → ภ.ง.ด.3
        public const int JuristicPerson = 2;    // นิติบุคคล → ภ.ง.ด.53
        public const int GovernmentAgency = 3;  // หน่วยงานราชการ
    }
}
