//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Admin.Pricing
{
    public partial class DynamicPricing
    {
        protected global::System.Web.UI.WebControls.Label lblCurrentMultiplier;
        protected global::System.Web.UI.WebControls.Label lblTodayOccupancy;
        protected global::System.Web.UI.WebControls.Label lblSuggestedPrice;
    }
}
