//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Mobile
{
    public partial class AddFriend
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Panel pnlMsg;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divMsg;
        protected global::System.Web.UI.WebControls.Literal litMsg;
        protected global::System.Web.UI.WebControls.Literal litOaName;
        protected global::System.Web.UI.WebControls.Literal litQr;
        protected global::System.Web.UI.WebControls.HyperLink lnkAdd;
        protected global::System.Web.UI.WebControls.Button btnRecheck;
    }
}
