//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Mobile
{
    public partial class LeaveMobile
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Literal litWho;
        protected global::System.Web.UI.WebControls.Panel pnlMsg;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divMsg;
        protected global::System.Web.UI.WebControls.Literal litMsg;
        protected global::System.Web.UI.WebControls.Literal litQuota;
        protected global::System.Web.UI.WebControls.Literal litTypes;
        protected global::System.Web.UI.WebControls.HiddenField hfLeaveType;
        protected global::System.Web.UI.WebControls.HiddenField hfMode;
        protected global::System.Web.UI.WebControls.TextBox txtStart;
        protected global::System.Web.UI.WebControls.TextBox txtEnd;
        protected global::System.Web.UI.WebControls.TextBox txtHalfDate;
        protected global::System.Web.UI.WebControls.HiddenField hfHalf;
        protected global::System.Web.UI.WebControls.TextBox txtReason;
        protected global::System.Web.UI.WebControls.FileUpload fuDoc;
        protected global::System.Web.UI.WebControls.Button btnSubmit;
        protected global::System.Web.UI.WebControls.Literal litHistory;
    }
}
