//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Mobile
{
    public partial class LeaveApprove
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Literal litWho;
        protected global::System.Web.UI.WebControls.Panel pnlMsg;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divMsg;
        protected global::System.Web.UI.WebControls.Literal litMsg;
        protected global::System.Web.UI.WebControls.Panel pnlDetail;
        protected global::System.Web.UI.WebControls.Literal litStatus;
        protected global::System.Web.UI.WebControls.Literal litDetail;
        protected global::System.Web.UI.WebControls.Literal litWarn;
        protected global::System.Web.UI.WebControls.Panel pnlActions;
        protected global::System.Web.UI.WebControls.Button btnApprove;
        protected global::System.Web.UI.WebControls.Button btnShowReject;
        protected global::System.Web.UI.WebControls.Panel pnlReject;
        protected global::System.Web.UI.WebControls.TextBox txtReject;
        protected global::System.Web.UI.WebControls.Button btnReject;
        protected global::System.Web.UI.WebControls.Button btnCancelReject;
        protected global::System.Web.UI.WebControls.Panel pnlPending;
        protected global::System.Web.UI.WebControls.Literal litPending;
    }
}
