//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Take_Time_BangPhra.Mobile
{
    public partial class LineLink
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Literal litAvatar;
        protected global::System.Web.UI.WebControls.Literal litLineName;
        protected global::System.Web.UI.WebControls.Panel pnlMsg;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divMsg;
        protected global::System.Web.UI.WebControls.Literal litMsg;
        protected global::System.Web.UI.WebControls.Panel pnlPick;
        protected global::System.Web.UI.WebControls.Literal litPeople;
        protected global::System.Web.UI.WebControls.HiddenField hfPicked;
        protected global::System.Web.UI.WebControls.Panel pnlConfirm;
        protected global::System.Web.UI.WebControls.Literal litPickedName;
        protected global::System.Web.UI.WebControls.TextBox txtPassword;
        protected global::System.Web.UI.WebControls.Button btnLinkNow;
        protected global::System.Web.UI.WebControls.Button btnAskApproval;
        protected global::System.Web.UI.WebControls.Button btnBack;
        protected global::System.Web.UI.WebControls.Panel pnlDone;
        protected global::System.Web.UI.WebControls.Literal litDoneTitle;
        protected global::System.Web.UI.WebControls.Literal litDoneText;
    }
}
