using MediatR;
using Microsoft.Extensions.Logging;
using TakeTime.Payment.Application.DTOs;
using TakeTime.Payment.Application.Services;

namespace TakeTime.Payment.Application.Commands;

/// <summary>
/// Command to generate a full tax invoice for a reservation.
/// Only available for VAT-registered tenants.
/// </summary>
public sealed class GenerateTaxInvoiceCommand : IRequest<TaxInvoiceDto>
{
    public Guid ReservationId { get; set; }
    public string BuyerName { get; set; } = string.Empty;
    public string? BuyerAddress { get; set; }
    public string? BuyerTaxId { get; set; }
    public string? BuyerBranch { get; set; }
    public string? IssuedBy { get; set; }
    public string? AuthorizedSignatory { get; set; }
}

/// <summary>
/// Handler for <see cref="GenerateTaxInvoiceCommand"/>. Generates a full tax invoice
/// compliant with Thai Revenue Department requirements for VAT-registered businesses.
/// </summary>
public sealed class GenerateTaxInvoiceCommandHandler : IRequestHandler<GenerateTaxInvoiceCommand, TaxInvoiceDto>
{
    private readonly ITaxInvoiceRepository _invoiceRepository;
    private readonly IReservationServiceClient _reservationClient;
    private readonly IPaymentRepository _paymentRepository;
    private readonly ITenantContext _tenantContext;
    private readonly VATCalculationService _vatService;
    private readonly ILogger<GenerateTaxInvoiceCommandHandler> _logger;

    public GenerateTaxInvoiceCommandHandler(
        ITaxInvoiceRepository invoiceRepository,
        IReservationServiceClient reservationClient,
        IPaymentRepository paymentRepository,
        ITenantContext tenantContext,
        VATCalculationService vatService,
        ILogger<GenerateTaxInvoiceCommandHandler> logger)
    {
        _invoiceRepository = invoiceRepository;
        _reservationClient = reservationClient;
        _paymentRepository = paymentRepository;
        _tenantContext = tenantContext;
        _vatService = vatService;
        _logger = logger;
    }

    public async Task<TaxInvoiceDto> Handle(GenerateTaxInvoiceCommand request, CancellationToken cancellationToken)
    {
        var tenantSettings = await _tenantContext.GetTenantSettingsAsync(cancellationToken);
        var currency = tenantSettings.Currency ?? "THB";

        // Validate tenant is VAT registered
        if (!tenantSettings.IsVATRegistered)
        {
            throw new InvalidOperationException(
                "Tax invoices can only be generated by VAT-registered businesses. " +
                "This tenant is not VAT registered.");
        }

        if (string.IsNullOrWhiteSpace(tenantSettings.BusinessTaxId))
        {
            throw new InvalidOperationException(
                "Business Tax ID is required to generate a tax invoice. " +
                "Please configure the business Tax ID in tenant settings.");
        }

        // Get reservation details
        var reservation = await _reservationClient.GetReservationAsync(
            request.ReservationId, cancellationToken)
            ?? throw new InvalidOperationException($"Reservation {request.ReservationId} not found.");

        // Generate invoice number
        var invoiceNumber = await GenerateInvoiceNumberAsync(tenantSettings.TenantId, cancellationToken);

        // Build line items
        var lineItems = new List<ReceiptItemDto>();
        var lineNumber = 1;

        foreach (var item in reservation.Items)
        {
            var itemVat = _vatService.CalculateVAT(item.TotalPrice, tenantSettings);

            lineItems.Add(new ReceiptItemDto
            {
                LineNumber = lineNumber++,
                Description = item.Description,
                ItemCode = item.ItemCode,
                Quantity = item.Quantity,
                UnitPrice = item.UnitPrice,
                TotalPrice = item.TotalPrice,
                VATAmount = itemVat.VATAmount,
                Currency = currency,
                Category = item.Category
            });
        }

        // Calculate totals
        var totalAmount = reservation.TotalAmount;
        var vatResult = _vatService.CalculateVAT(totalAmount, tenantSettings);

        var invoice = new TaxInvoiceDto
        {
            Id = Guid.NewGuid(),
            InvoiceNumber = invoiceNumber,
            TenantId = tenantSettings.TenantId,
            ReservationId = request.ReservationId,
            ReservationNumber = reservation.ReservationNumber,

            // Seller
            SellerName = tenantSettings.BusinessName ?? tenantSettings.TenantName,
            SellerAddress = tenantSettings.BusinessAddress,
            SellerTaxId = tenantSettings.BusinessTaxId,
            SellerPhone = tenantSettings.BusinessPhone,
            SellerBranch = tenantSettings.BusinessBranch ?? "Head Office",

            // Buyer
            BuyerName = request.BuyerName,
            BuyerAddress = request.BuyerAddress,
            BuyerTaxId = request.BuyerTaxId,
            BuyerBranch = request.BuyerBranch,

            // Items
            Items = lineItems,

            // Totals
            SubTotal = lineItems.Sum(i => i.TotalPrice),
            DiscountAmount = 0,
            AmountBeforeVAT = vatResult.AmountBeforeVAT,
            VATRate = tenantSettings.VATRate,
            VATAmount = vatResult.VATAmount,
            TotalAmount = totalAmount,
            Currency = currency,
            TotalAmountInWords = ConvertAmountToWords(totalAmount, currency),

            // Metadata
            InvoiceDate = DateTime.UtcNow,
            IssuedBy = request.IssuedBy,
            AuthorizedSignatory = request.AuthorizedSignatory,
            CreatedAt = DateTime.UtcNow
        };

        // Persist the invoice
        await _invoiceRepository.CreateAsync(invoice, cancellationToken);

        _logger.LogInformation(
            "Tax invoice {InvoiceNumber} generated for reservation {ReservationNumber}, tenant {TenantId}",
            invoiceNumber, reservation.ReservationNumber, tenantSettings.TenantId);

        return invoice;
    }

    private async Task<string> GenerateInvoiceNumberAsync(string tenantId, CancellationToken cancellationToken)
    {
        var today = DateTime.UtcNow;
        var prefix = $"INV-{today:yyyyMMdd}";
        var count = await _invoiceRepository.GetTodayInvoiceCountAsync(tenantId, cancellationToken);
        return $"{prefix}-{(count + 1):D4}";
    }

    private static string ConvertAmountToWords(decimal amount, string currency)
    {
        var wholePart = (long)Math.Floor(amount);
        var fractionPart = (int)Math.Round((amount - wholePart) * 100);

        var currencyName = currency switch
        {
            "THB" => "Baht",
            "USD" => "Dollars",
            "EUR" => "Euros",
            _ => currency
        };

        var fractionName = currency switch
        {
            "THB" => "Satang",
            "USD" => "Cents",
            "EUR" => "Cents",
            _ => "units"
        };

        if (fractionPart == 0)
        {
            return $"{NumberToWords(wholePart)} {currencyName} Only";
        }

        return $"{NumberToWords(wholePart)} {currencyName} and {NumberToWords(fractionPart)} {fractionName}";
    }

    private static string NumberToWords(long number)
    {
        if (number == 0) return "Zero";

        if (number < 0) return $"Minus {NumberToWords(Math.Abs(number))}";

        var words = string.Empty;

        if (number / 1_000_000 > 0)
        {
            words += NumberToWords(number / 1_000_000) + " Million ";
            number %= 1_000_000;
        }

        if (number / 1_000 > 0)
        {
            words += NumberToWords(number / 1_000) + " Thousand ";
            number %= 1_000;
        }

        if (number / 100 > 0)
        {
            words += NumberToWords(number / 100) + " Hundred ";
            number %= 100;
        }

        if (number > 0)
        {
            var units = new[]
            {
                "", "One", "Two", "Three", "Four", "Five", "Six", "Seven",
                "Eight", "Nine", "Ten", "Eleven", "Twelve", "Thirteen",
                "Fourteen", "Fifteen", "Sixteen", "Seventeen", "Eighteen", "Nineteen"
            };

            var tens = new[]
            {
                "", "", "Twenty", "Thirty", "Forty", "Fifty",
                "Sixty", "Seventy", "Eighty", "Ninety"
            };

            if (number < 20)
            {
                words += units[number];
            }
            else
            {
                words += tens[number / 10];
                if (number % 10 > 0)
                    words += "-" + units[number % 10];
            }
        }

        return words.Trim();
    }
}
